version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################

  app:
    image: checkmk/${TYPE:-check-mk-raw}:${VERSION:-2.0.0-latest}
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          # - "node.id==${NODE_ID}"
          - "node.role==${NODE_ROLE:-manager}"
      restart_policy:
        condition: on-failure
    ports:
      - target: 5000
        published: 8080
        protocol: tcp
        mode: host
    tmpfs:
      - /opt/cmk/tmp:uid=1000,gid=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/omd/sites
    networks:
      default: {}
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}

volumes:
  data: {}
