---
version: "3.8"

################################################################################
################################################################################
################################################################################

x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.paperless.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.paperless.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.paperless.tls=true
    - traefik.http.routers.paperless.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.paperless.service=paperless
    - traefik.http.services.paperless.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.paperless.loadbalancer.server.port=${PORT:-8000}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-1}
      memory: ${RESOURCES_LIMITS_MEMORY:-1g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: .env
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    default: {}
  healthcheck:
    disable: true
  restart: always

################################################################################
################################################################################
################################################################################
services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  paperless:
    # https://github.com/paperless-ngx/paperless-ngx/pkgs/container/paperless-ngx
    image: ghcr.io/paperless-ngx/paperless-ngx:${VERSION_PAPERLESS:-1.17.4}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    cap_add:
      - DAC_OVERRIDE
      - CHOWN
      - SETGID
      - SETUID
    secrets:
      - mariadb_password_file
      - paperless_admin_password_file
      - paperless_secret_key
    environment:
      PAPERLESS_URL: https://${DOMAIN?domain variable not set}
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBPORT: 3306
      PAPERLESS_DBUSER: ${MARIADB_USER:-paperless}
      PAPERLESS_DBPASS_FILE: /run/secrets/mariadb_password_file
      PAPERLESS_ADMIN_USER: ${PAPERLESS_ADMIN_USER:-groot}
      PAPERLESS_ADMIN_PASSWORD_FILE: /run/secrets/paperless_admin_password_file
      PAPERLESS_SECRET_KEY: /run/secrets/paperless_secret_key
      PAPERLESS_OCR_LANGUAGE: eng
      # https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
      PAPERLESS_OCR_LANGUAGES: eng deu
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - export:/usr/src/paperless/export
      - consume:/usr/src/paperless/consume
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      default: {}
      proxy: {}

  ##############################################################################
  ##############################################################################
  ##############################################################################
  db:
    # https://hub.docker.com/_/mariadb
    image: mariadb:${VERSION_MARIADB:-11.2.2}
    <<: *basic
    deploy:
      <<: *basic-deploy
    cap_add:
      - SYS_NICE
      - DAC_OVERRIDE
      - CHOWN
      - SETGID
      - SETUID
    secrets:
      - mariadb_password_file
      - mariadb_root_password_file
    environment:
      MARIADB_HOST: ${MARIADB_HOST:-paperless}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-paperless}
      MARIADB_USER: ${MARIADB_USER:-paperless}
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_password_file
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password_file
    volumes:
      - db:/var/lib/mysql
    command:
      - --log-bin=mysql-bin
      - --expire-logs-days=7

  ##############################################################################
  ##############################################################################
  ##############################################################################
  redis:
    # https://hub.docker.com/_/redis
    image: redis:${VERSION_REDIS:-7.2.3-alpine}
    <<: *basic
    deploy:
      <<: *basic-deploy
    cap_add:
      - SETGID
      - SETUID
    volumes:
      - redis:/data
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 5s
      interval: 10s
      retries: 5
      timeout: 3s

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
    driver_opts:
      encrypted: "true"
  proxy:
    external: true

volumes:
  data: {}
  media: {}
  export: {}
  consume: {}
  db: {}
  redis: {}

secrets:
  mariadb_password_file:
    file: config/secrets/mariadb_password_file.txt
  mariadb_root_password_file:
    file: config/secrets/mariadb_root_password_file.txt
  paperless_admin_password_file:
    file: config/secrets/paperless_admin_password_file.txt
  paperless_secret_key:
    file: config/secrets/paperless_secret_key.txt
