---
type: http

name: http_elasticsearch # this must match with the registered plugin in the profile
log_level: debug # Options include: trace, debug, info, warn, error, off

format: |-
  {{ range .}}
   {"index": { "_index": "crowdsec"} }
   {{.|toJson}}
  {{ end }}

url: http://elasticsearch:9200/_bulk

method: POST
headers:
  Content-Type: "application/json"
  Authorization: "Basic ZWxhc3RpYzp9bU9SQHd1Yjwxbi4wLmNDZFZCeg=="
