---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.swarm.lbswarm=${LB_SWARM:-true}
    - traefik.swarm.network=proxy
    - traefik.http.routers.nextcloud.entrypoints=https
    - traefik.http.routers.nextcloud.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.nextcloud.tls=true
    - traefik.http.routers.nextcloud.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.nextcloud.service=nextcloud
    - traefik.http.services.nextcloud.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.nextcloud.loadbalancer.server.port=${PORT:-80}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-1}
      memory: ${RESOURCES_LIMITS_MEMORY:-2g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  user: "${GID:-www-data}:${UID:-www-data}"
  # cap_add:
  #   # https://dockerlabs.collabnix.com/advanced/security/capabilities/
  #   - CHOWN
  #   - DAC_OVERRIDE
  #   - DAC_READ_SEARCH
  #   - SETGID
  #   - SETUID
  #   - NET_ADMIN
  #   - NET_RAW
  #   - NET_BIND_SERVICE
  #   - NET_BROADCAST
  #   - SYS_MODULE
  #   - SYS_NICE
  #   - AUDIT_CONTROL
  #   - AUDIT_READ
  #   # --------------------------
  #   - FOWNER
  #   - FSETID
  #   - KILL
  #   - SETPCAP
  #   - LINUX_IMMUTABLE
  #   - IPC_LOCK
  #   - IPC_OWNER
  #   - SYS_RAWIO
  #   - SYS_CHROOT
  #   - SYS_PTRACE
  #   - SYS_PACCT
  #   - SYS_ADMIN
  #   - SYS_BOOT
  #   - SYS_RESOURCE
  #   - SYS_TIME
  #   - SYS_TTY_CONFIG
  #   - MKNOD
  #   - LEASE
  #   - AUDIT_WRITE
  #   - SETFCAP
  #   - MAC_OVERRIDE
  #   - MAC_ADMIN
  #   - SYSLOG
  #   - WAKE_ALARM
  #   - BLOCK_SUSPEND
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    default: {}
    mysql: {}
    proxy: {}
  healthcheck:
    disable: true
  restart: always

x-nextcloud-env: &nextcloud-env
  VIRTUAL_HOST: ${VIRTUAL_HOST:-}

  NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER:-admin}
  NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/nextcloud_admin_password

  MYSQL_HOST: ${MYSQL_HOST:-mysql}
  MYSQL_DATABASE: ${MYSQL_DATABASE:-nextcloud}
  MYSQL_USER: ${MYSQL_USER:-nextcloud}
  MYSQL_PASSWORD_FILE: /run/secrets/mysql_password

  PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-1G}
  PHP_UPLOAD_LIMIT: ${PHP_UPLOAD_LIMIT:-1G}

  TRUSTED_PROXIES: ${TRUSTED_PROXIES:-10.0.0.0/8}
  OVERWRITEPROTOCOL: https
  OVERWRITEHOST: ${DOMAIN?domain variable not set}
  OVERWRITECLIURL: https://${DOMAIN?domain variable not set}

  REDIS_HOST: ${REDIS_HOST:-redis}
  REDIS_HOST_PORT: ${REDIS_HOST_PORT:-6379}

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  nextcloud:
    # https://hub.docker.com/_/nextcloud
    image: nextcloud:${VERSION_NEXTCLOUD:-27.1.3-apache}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    # cap_add:
    #   - MKNOD
    # read_only: true
    secrets:
      - nextcloud_admin_password
      - mysql_password
    environment:
      <<: *nextcloud-env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - nextcloud_html:/var/www/html
      - nextcloud_data:/var/www/data
    healthcheck:
      test: ["CMD", "curl", "-f", "${PROTOCOL:-http}://127.0.0.1:${PORT:-80}"]
      interval: 30s
      timeout: 10s
      retries: 5

  ##############################################################################
  ##############################################################################
  ##############################################################################
  redis:
    # https://hub.docker.com/_/redis
    image: redis:${VERSION_REDIS:-7.2.2-alpine3.18}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: *basic-deploy
    user: "999:999"
    # cap_add:
    #   - SETUID
    #   - SETGID
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - redis:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    networks:
      default: {}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ##############################################################################
  ##############################################################################
  ##############################################################################
  cron:
    # https://hub.docker.com/_/nextcloud
    image: nextcloud:${VERSION_NEXTCLOUD_CRON:-27.1.3-fmp}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: *basic-deploy
    # cap_add:
    #   - SETUID
    #   - SETGID
    secrets:
      - nextcloud_admin_password
      - mysql_password
    environment:
      <<: *nextcloud-env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - nextcloud_html:/var/www/html
      - nextcloud_data:/var/www/data
    entrypoint: sh -c 'while true; do php -f /var/www/html/cron.php; sleep 5m; done'
    networks:
      default: {}
      mysql: {}

################################################################################
################################################################################
################################################################################
networks:
  default:
    # name: proxy
    driver: ${NETWORK_MODE:-overlay}
    attachable: true
    driver_opts:
      encrypted: "true"
  mysql:
    # external: true
    name: mysql
    driver: ${NETWORK_MODE:-overlay}
    attachable: true
    driver_opts:
      encrypted: "true"
  proxy:
    external: true

volumes:
  nextcloud_html: {}
  nextcloud_data: {}
  redis: {}

secrets:
  nextcloud_admin_password:
    file: config/secrets/nextcloud_admin_password.txt
  mysql_password:
    file: config/secrets/mysql_password.txt
