---
version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: on-failure
    ports:
      # - target: 9000
      #   published: ${PORT_HTTP:-9000}
      #   protocol: tcp
      #   mode: host
      - target: 9443
        published: ${PORT_HTTPS:-9443}
        protocol: tcp
        mode: host
      - target: 8000
        published: ${PORT_OTHER:-8000}
        protocol: tcp
        mode: host
    configs:
      - source: crt_config
        target: /certs/selfsigned.crt
      - source: key_config
        target: /certs/selfsigned.key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/data
    command: -H tcp://tasks.agent:9001 --tlsskipverify --tls-cert /certs/selfsigned.crt --tls-key /certs/selfsigned.key
    networks:
      default: {}

  agent:
    image: portainer/agent:latest
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      default: {}
  # registry:
  #   image: registry:latest
  #   deploy:
  #     mode: global
  #     placement:
  #       constraints:
  #         - "node.role==manager"
  #     restart_policy:
  #       condition: on-failure
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  #   volumes:
  #     - registry:/data
  #   networks:
  #     default: {}

networks:
  default:
    driver: ${NETWORK_MODE:-overlay}
    attachable: true

volumes:
  data: {}
  # registry: {}

configs:
  crt_config:
    file: $PWD/config/ssl/selfsigned.crt
  key_config:
    file: $PWD/config/ssl/selfsigned.key
