---
services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  telegraf:
    image: telegraf:${VERSION:-latest}
    env_file: .env
    # run to check "$(stat -c '%g' /var/run/docker.sock)"
    user: telegraf:999
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: global
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=${LB_SWARM:-true}
        - traefik.docker.network=proxy
        - traefik.http.routers.telegraf.entrypoints=https
        - traefik.http.routers.telegraf.rule=Host(`${DOMAIN?domain variable not set}`)
        - traefik.http.routers.telegraf.tls=true
        - traefik.http.routers.telegraf.service=telegraf
        - traefik.http.services.telegraf.loadbalancer.server.scheme=${PROTOCOL:-http}
        - traefik.http.services.telegraf.loadbalancer.server.port=${PORT:-8125}
        - traefik.http.routers.telegraf.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    # ports:
    #   - target: 8125
    #     published: ${PORT:-8125}
    #     protocol: udp
    #     mode: host
    environment:
      HOST_MOUNT_PREFIX: /hostfs
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_ETC: /hostfs/etc
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
    configs:
      - source: telegraf_config
        target: /etc/telegraf/telegraf.conf
        mode: 0440
        # uid: "1000"
        gid: "999"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/hostfs/sys:ro
      - /proc:/hostfs/proc:ro
      - /etc:/hostfs/etc:ro
      - /var:/hostfs/var:ro
      - /run:/hostfs/run:ro
    networks:
      # default: {}
      proxy: {}
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  # default:
  #   driver: ${NETWORK_MODE:-bridge}
  #   attachable: true
  proxy:
    external: true

configs:
  telegraf_config:
    file: $PWD/config/telegraf.conf
