---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.swarm.lbswarm=${LB_SWARM:-true}
    - traefik.swarm.network=proxy
    - traefik.http.routers.graylog.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.graylog.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.graylog.tls=true
    - traefik.http.routers.graylog.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.graylog.service=graylog
    - traefik.http.services.graylog.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.graylog.loadbalancer.server.port=${PORT:-9000}

    - traefik.tcp.routers.graylog-syslog.entrypoints=${SYSLOG_ENTRYPOINT:-syslog-tls}
    - traefik.tcp.routers.graylog-syslog.rule=HostSNI(`${SYSLOG_DOMAIN_TLS?domain variable not set}`)
    - traefik.tcp.routers.graylog-syslog.tls=true
    - traefik.tcp.routers.graylog-syslog.tls.passthrough=false
    - traefik.tcp.services.graylog-syslog.loadbalancer.server.port=${SYSLOG_PORT_TLS:-5140}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: any

x-basic-deploy-resources-graylog: &basic-deploy-resources-graylog
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-1.5}
      memory: ${RESOURCES_LIMITS_MEMORY:-2g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic-deploy-resources-datanode: &basic-deploy-resources-datanode
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS_GRAYLOG_DATANODE:-2}
      memory: ${RESOURCES_LIMITS_MEMORY_GRAYLOG_DATANODE:-3g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS_GRAYLOG_DATANODE:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY_GRAYLOG_DATANODE:-32m}

x-basic-deploy-resources-mongodb: &basic-deploy-resources-mongodb
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS_MONGODB:-1}
      memory: ${RESOURCES_LIMITS_MEMORY_MONGODB:-512m}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS_MONGODB:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY_MONGODB:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  # cap_add:
  #   - CHOWN
  #   - SETGID
  #   - SETUID
  # cap_drop: [ "ALL" ]
  # security_opt:
  #   - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  networks:
    default: {}
  healthcheck:
    disable: true
  tmpfs:
    - /tmp
    - /run
    - /run/lock
  restart: always

################################################################################
################################################################################
################################################################################
services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  graylog1:
    hostname: "graylog1"
    # https://hub.docker.com/r/graylog/graylog
    image: graylog/graylog:${VERSION_GRAYLOG:-6.2}
    <<: *basic
    deploy:
      <<: [*basic-deploy, *basic-deploy-resources-graylog, *basic-deploy-labels]
    ports:
      # # Graylog web interface and REST API
      # - target: 9000
      #   published: ${PORT:-9000}
      #   protocol: tcp
      #   mode: host
      # NETFLOW TCP
      - target: 2055
        published: ${PORT_NETFLOW:-2055}
        protocol: tcp
        mode: host
      # NETFLOW UDP
      - target: 2055
        published: ${PORT_NETFLOW:-2055}
        protocol: udp
        mode: host
      # BEATS TCP
      - target: 5044
        published: ${PORT_BEATS:-5044}
        protocol: tcp
        mode: host
      # # BEATS UDP
      # - target: 5044
      #   published: ${PORT_BEATS:-5044}
      #   protocol: udp
      #   mode: host
      # Syslog TCP
      - target: 5140
        published: ${PORT_SYSLOG:-5140}
        protocol: tcp
        mode: host
      # Syslog UDP
      - target: 5140
        published: ${PORT_SYSLOG:-5140}
        protocol: udp
        mode: host
      # RAW TCP
      - target: 5555
        published: ${PORT_RAW:-5555}
        protocol: tcp
        mode: host
      # RAW UDP
      - target: 5555
        published: ${PORT_RAW:-5555}
        protocol: udp
        mode: host
      # GELF TCP
      - target: 12201
        published: ${PORT_GELF:-12201}
        protocol: tcp
        mode: host
      # GELF UDP
      - target: 12201
        published: ${PORT_GELF:-12201}
        protocol: udp
        mode: host
      # Forwarder data
      - target: 13301
        published: ${PORT_FORWARDER_DATA:-13301}
        protocol: tcp
        mode: host
      # Forwarder config
      - target: 13302
        published: ${PORT_FORWARDER_CONFIG:-13302}
        protocol: tcp
        mode: host
    secrets:
      - graylog_password_secret
      - graylog_root_password_sha2
    environment:
      GRAYLOG_PASSWORD_SECRET__FILE: /run/secrets/graylog_password_secret
      GRAYLOG_ROOT_PASSWORD_SHA2__FILE: /run/secrets/graylog_root_password_sha2
      GRAYLOG_HTTP_EXTERNAL_URI: ${GRAYLOG_HTTP_EXTERNAL_URI:-http://127.0.0.1:9000/}
      # GRAYLOG_HTTP_PUBLISH_URI: ${GRAYLOG_HTTP_PUBLISH_URI}
      GRAYLOG_MONGODB_URI: mongodb://mongodb1:27017/graylog
      GRAYLOG_HTTP_BIND_ADDRESS: 0.0.0.0:9000
      GRAYLOG_NODE_ID_FILE: /usr/share/graylog/data/config/node-id
      GRAYLOG_REPORT_DISABLE_SANDBOX: ${GRAYLOG_REPORT_DISABLE_SANDBOX:-true}

      # # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      # GRAYLOG_SERVER_JAVA_OPTS: -Xms${RESOURCES_LIMITS_MEMORY:-2g} -Xmx${RESOURCES_LIMITS_MEMORY:-2g} -XX:NewRatio=1 -server -XX:+ResizeTLAB -XX:-OmitStackTraceInFastThrow

      GRAYLOG_TRANSPORT_EMAIL_ENABLED: ${GRAYLOG_TRANSPORT_EMAIL_ENABLED:-true}
      GRAYLOG_TRANSPORT_EMAIL_HOSTNAME: ${GRAYLOG_TRANSPORT_EMAIL_HOSTNAME:-smtp}
      GRAYLOG_TRANSPORT_EMAIL_PORT: ${GRAYLOG_TRANSPORT_EMAIL_PORT:-465}
      GRAYLOG_TRANSPORT_EMAIL_USE_AUTH: ${GRAYLOG_TRANSPORT_EMAIL_USE_AUTH:-true}
      GRAYLOG_TRANSPORT_EMAIL_USE_TLS: ${GRAYLOG_TRANSPORT_EMAIL_USE_TLS:-true}
      GRAYLOG_TRANSPORT_EMAIL_USE_SSL: ${GRAYLOG_TRANSPORT_EMAIL_USE_SSL:-false}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - graylog_data_01:/usr/share/graylog/data/data
      - graylog_config_01:/usr/share/graylog/data/config
      - graylog_journal_01:/usr/share/graylog/data/journal
    entrypoint: /usr/bin/tini -- wait-for-it datanode1:8999 -- /docker-entrypoint.sh
    networks:
      default: {}
      graylog: {}
      proxy: {}

  ##############################################################################
  ##############################################################################
  ##############################################################################
  datanode1:
    hostname: "datanode1"
    # https://hub.docker.com/r/graylog/graylog-datanode
    image: graylog/graylog-datanode:${VERSION_GRAYLOG:-6.2}
    <<: *basic
    deploy:
      <<: [*basic-deploy, *basic-deploy-resources-datanode]
    secrets:
      - graylog_password_secret
    environment:
      GRAYLOG_DATANODE_ROOT_USERNAME: admin
      GRAYLOG_DATANODE_PASSWORD_SECRET__FILE: /run/secrets/graylog_password_secret
      GRAYLOG_DATANODE_MONGODB_URI: mongodb://mongodb1:27017/graylog
      GRAYLOG_DATANODE_DATA_DIR: /var/lib/graylog-datanode
      GRAYLOG_DATANODE_NODE_ID_FILE: /var/lib/graylog-datanode/node-id
      opensearch.bootstrap.system_call_filter: "false"
      OPENSEARCH_BOOTSTRAP_SYSTEM_CALL_FILTER: "false"
      GRAYLOG_DATANODE_OPENSEARCH_BOOTSTRAP_SYSTEM_CALL_FILTER: "false"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - graylog_datanode_01:/var/lib/graylog-datanode

  datanode2:
    hostname: "datanode2"
    # https://hub.docker.com/r/graylog/graylog-datanode
    image: graylog/graylog-datanode:${VERSION_GRAYLOG:-6.2}
    <<: *basic
    deploy:
      <<: [*basic-deploy, *basic-deploy-resources-datanode]
    secrets:
      - graylog_password_secret
    environment:
      GRAYLOG_DATANODE_ROOT_USERNAME: admin
      GRAYLOG_DATANODE_PASSWORD_SECRET__FILE: /run/secrets/graylog_password_secret
      GRAYLOG_DATANODE_MONGODB_URI: mongodb://mongodb1:27017/graylog
      GRAYLOG_DATANODE_DATA_DIR: /var/lib/graylog-datanode
      GRAYLOG_DATANODE_NODE_ID_FILE: /var/lib/graylog-datanode/node-id
      opensearch.bootstrap.system_call_filter: "false"
      OPENSEARCH_BOOTSTRAP_SYSTEM_CALL_FILTER: "false"
      GRAYLOG_DATANODE_OPENSEARCH_BOOTSTRAP_SYSTEM_CALL_FILTER: "false"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - graylog_datanode_02:/var/lib/graylog-datanode

  datanode3:
    hostname: "datanode3"
    # https://hub.docker.com/r/graylog/graylog-datanode
    image: graylog/graylog-datanode:${VERSION_GRAYLOG:-6.2}
    <<: *basic
    deploy:
      <<: [*basic-deploy, *basic-deploy-resources-datanode]
    secrets:
      - graylog_password_secret
    environment:
      GRAYLOG_DATANODE_ROOT_USERNAME: admin
      GRAYLOG_DATANODE_PASSWORD_SECRET__FILE: /run/secrets/graylog_password_secret
      GRAYLOG_DATANODE_MONGODB_URI: mongodb://mongodb1:27017/graylog
      GRAYLOG_DATANODE_DATA_DIR: /var/lib/graylog-datanode
      GRAYLOG_DATANODE_NODE_ID_FILE: /var/lib/graylog-datanode/node-id
      opensearch.bootstrap.system_call_filter: "false"
      OPENSEARCH_BOOTSTRAP_SYSTEM_CALL_FILTER: "false"
      GRAYLOG_DATANODE_OPENSEARCH_BOOTSTRAP_SYSTEM_CALL_FILTER: "false"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - graylog_datanode_03:/var/lib/graylog-datanode

  ##############################################################################
  ##############################################################################
  ##############################################################################
  mongodb1:
    hostname: "mongodb1"
    # https://hub.docker.com/_/mongo
    image: mongo:${VERSION_MONGODB:-8.0.8}
    <<: *basic
    deploy:
      <<: [*basic-deploy, *basic-deploy-resources-mongodb]
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
    # command: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - mongodb_data_01:/data/db
      - mongodb_config_01:/data/configdb

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
    driver_opts:
      encrypted: "true"
  graylog:
    name: graylog
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
    driver_opts:
      encrypted: "true"
  proxy:
    external: true

volumes:
  graylog_data_01: {}
  graylog_config_01: {}
  graylog_journal_01: {}
  graylog_datanode_01: {}
  graylog_datanode_02: {}
  graylog_datanode_03: {}
  mongodb_data_01: {}
  mongodb_config_01: {}

secrets:
  graylog_password_secret:
    file: config/secrets/graylog_password_secret.txt
  graylog_root_password_sha2:
    file: config/secrets/graylog_root_password_sha2.txt
