---
# Pre-commit configuration
# For details, visit: https://pre-commit.com/hooks.html

repos:
  # Codespell for spelling corrections
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=ihs,ro,fo,discoverd
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
        exclude_types:
          - csv
          - json

  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # - id: end-of-file-fixer
      - id: check-toml
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # Prettier for code formatting
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.5.1
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5
          - prettier-plugin-sort-json@3.1.0
        exclude_types:
          - python
        # types_or:
        #   - yaml
        #   - json5

  # Secret detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.0
    hooks:
      - id: gitleaks

  # YAML Linting
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint

  # # Dockerfile linting #########################################################
  # - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  #   rev: v0.1.0
  #   hooks:
  #     - id: dockerfilelint
  #       stages: [pre-commit]
