---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.kimai.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.kimai.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.kimai.tls=true
    - traefik.http.routers.kimai.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.kimai.service=kimai
    - traefik.http.services.kimai.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.kimai.loadbalancer.server.port=${PORT:-8001}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: any
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-0.5}
      memory: ${RESOURCES_LIMITS_MEMORY:-500m}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  networks:
    default: {}
  healthcheck:
    disable: true
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  kimai:
    # https://hub.docker.com/r/kimai/kimai2
    image: kimai/kimai2:${VERSION_KIMAI:-apache-2.33.0}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    # configs:
    #   - source: local_config
    #     target: /opt/kimai/config/packages/local.yaml
    environment:
      TRUSTED_HOSTS: ${DOMAIN?domain variable not set},localhost,127.0.0.1
      DATABASE_URL: mysql://${MARIADB_USER:-kimai}:${DB_PASS}@mariadb:3306/${MARIADB_DATABASE:-kimai}?charset=utf8&serverVersion=${VERSION_MARIADB:-11.3.2}
      # DB_TYPE: mysql
      # DB_USER: ${MARIADB_USER:-kimai}
      # DB_PASS: ${DB_PASS}
      # DB_HOST: mariadb
      # DB_PORT: 3306
      # DB_BASE: ${MARIADB_DATABASE:-kimai}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/opt/kimai/var
      - plugins:/opt/kimai/var/plugins
    networks:
      default: {}
      proxy: {}

  ##############################################################################
  ##############################################################################
  ##############################################################################
  mariadb:
    # https://hub.docker.com/_/mariadb
    image: mariadb:${VERSION_MARIADB:-11.7.2}
    <<: *basic
    deploy:
      <<: *basic-deploy
      resources:
        limits:
          cpus: ${RESOURCES_LIMITS_CPUS_MARIADB:-1}
          memory: ${RESOURCES_LIMITS_MEMORY_MARIADB:-512M}
        reservations:
          cpus: ${RESOURCES_RESERVATIONS_CPUS_MARIADB:-0.001}
          memory: ${RESOURCES_RESERVATIONS_MEMORY_MARIADB:-32m}
    cap_add:
      - SETUID
      - SETGID
      - DAC_OVERRIDE
    secrets:
      - mariadb_user_password
    environment:
      TZ: ${TZ:-Europe/Berlin}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-kimai}
      MARIADB_USER: ${MARIADB_USER:-kimai}
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_user_password
      MARIADB_RANDOM_ROOT_PASSWORD: ${MARIADB_RANDOM_ROOT_PASSWORD:-true}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - mariadb:/var/lib/mysql
    command:
      - --log-bin=mysql-bin
      - --expire-logs-days=7
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 2s
      interval: 5s
      timeout: 3s
      retries: 5

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-overlay}
    attachable: true
    driver_opts:
      encrypted: "true"
  proxy:
    external: true

# configs:
#   local_config:
#     file: $PWD/config/local.yaml

volumes:
  data: {}
  plugins: {}
  mariadb: {}

secrets:
  mariadb_user_password:
    file: config/secrets/mariadb_user_password.txt
