---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.attack-navigator.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.attack-navigator.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.attack-navigator.tls=true
    - traefik.http.routers.attack-navigator.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.attack-navigator.service=attack-navigator
    - traefik.http.services.attack-navigator.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.attack-navigator.loadbalancer.server.port=${PORT:-80}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-0.5}
      memory: ${RESOURCES_LIMITS_MEMORY:-500m}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  cap_add:
    - CHOWN
    - SETGID
    - SETUID
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    proxy: {}
  healthcheck:
    disable: true
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  attacknavigator:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-2024}
        VERSION: ${VERSION:-latest}
        # https://hub.docker.com/_/node
        VERSION_NODE: ${VERSION_NODE:-23.2.0}
        # https://hub.docker.com/_/nginx
        VERSION_NGINX: ${VERSION_NGINX:-1.27.2}
    # https://github.com/mitre-attack/attack-navigator
    image: attacknavigator:${VERSION:-latest}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    # ports:
    #   - target: ${PORT:-80}
    #     published: ${PORT_PUBLISH:-80}
    #     protocol: tcp
    #     mode: host
    environment:
      NGINX_HOST: ${DOMAIN?domain variable not set}
      NGINX_PORT: 80
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

################################################################################
################################################################################
################################################################################
networks:
  proxy:
    external: true
