---
version: "3.8"

################################################################################
################################################################################
################################################################################

x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.attack-navigator.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.attack-navigator.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.attack-navigator.tls=true
    - traefik.http.routers.attack-navigator.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.attack-navigator.service=attack-navigator
    - traefik.http.services.attack-navigator.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.attack-navigator.loadbalancer.server.port=${PORT:-4200}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-0.5}
      memory: ${RESOURCES_LIMITS_MEMORY:-500m}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: .env
  # cap_add:
  #   - CHOWN
  #   - DAC_OVERRIDE
  #   - DAC_READ_SEARCH
  #   - SETGID
  #   - SETUID
  #   - NET_ADMIN
  #   - NET_RAW
  #   - NET_BIND_SERVICE
  #   - NET_BROADCAST
  #   - SYS_MODULE
  #   - SYS_NICE
  #   - AUDIT_CONTROL
  #   - AUDIT_READ
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    proxy: {}
  healthcheck:
    disable: true
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-2024}
        VERSION: ${VERSION:-latest}
        VERSION_NODE: ${VERSION_NODE:-21}
    image: attacknavigator:${VERSION:-latest}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    # ports:
    #   - target: ${PORT:-4200}
    #     published: ${PORT_PUBLISH:-4200}
    #     protocol: tcp
    #     mode: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

################################################################################
################################################################################
################################################################################
networks:
  proxy:
    external: true
