version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  openspeedtest:
    image: openspeedtest/latest:${VERSION:-latest}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          # - "node.id==${NODE_ID}"
          - "node.role==${NODE_ROLE:-manager}"
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=${LB_SWARM:-true}
        - traefik.docker.network=proxy
        - traefik.http.routers.openspeedtest.entrypoints=https
        - traefik.http.routers.openspeedtest.rule=Host(`${DOMAIN?domain variable not set}`)
        - traefik.http.routers.openspeedtest.tls=true
        - traefik.http.routers.openspeedtest.service=openspeedtest
        - traefik.http.services.openspeedtest.loadbalancer.server.scheme=${PROTOCOL:-http}
        - traefik.http.services.openspeedtest.loadbalancer.server.port=${PORT:-3000}
        - traefik.http.routers.openspeedtest.middlewares=${MIDDLEWARE_SECURED:-home-secured@file}
    # ports:
    #   - target: 3000
    #     published: ${PORT:-3000}
    #     protocol: tcp
    #     mode: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      # default: {}
      proxy: {}
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  # default:
  #   driver: ${NETWORK_MODE:-bridge}
  #   attachable: true
  proxy:
    external: true
