---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.swarm.lbswarm=${LB_SWARM:-true}
    - traefik.swarm.network=proxy
    - traefik.http.routers.librenms.entrypoints=https
    - traefik.http.routers.librenms.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.librenms.tls=true
    - traefik.http.routers.librenms.service=librenms
    - traefik.http.services.librenms.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.librenms.loadbalancer.server.port=${PORT:-8000}
    - traefik.http.routers.librenms.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      cpus: "2"
      memory: 2g
    reservations:
      cpus: "0.001"
      memory: 32M

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    default: {}
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  librenms:
    image: librenms/librenms:${VERSION_LIBRENMS:-26.8.2}
    <<: *basic
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - FOWNER
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    # ports:
    #   - target: ${PORT:-8000}
    #     published: ${PORT_PUBLISH:-8000}
    #     protocol: tcp
    #     mode: host
    secrets:
      - librenms_db_pass
    environment:
      TZ: ${TZ:-Europe/Berlin}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}

      LISTEN_IPV6: ${LISTEN_IPV6:-false}
      LIBRENMS_SNMP_COMMUNITY: ${LIBRENMS_SNMP_COMMUNITY:-}

      MEMORY_LIMIT: ${MEMORY_LIMIT:-256M}
      MAX_INPUT_VARS: ${MAX_INPUT_VARS:-1000}
      UPLOAD_MAX_SIZE: ${UPLOAD_MAX_SIZE:-16M}
      OPCACHE_MEM_SIZE: ${OPCACHE_MEM_SIZE:-128}
      REAL_IP_FROM: ${REAL_IP_FROM:-0.0.0.0/32}
      REAL_IP_HEADER: ${REAL_IP_HEADER:-X-Forwarded-For}
      LOG_IP_VAR: ${LOG_IP_VAR:-http_x_forwarded_for}

      CACHE_DRIVER: ${CACHE_DRIVER:-redis}
      SESSION_DRIVER: ${SESSION_DRIVER:-redis}
      REDIS_HOST: valkey

      LIBRENMS_WEATHERMAP: ${LIBRENMS_WEATHERMAP:-false}
      LIBRENMS_WEATHERMAP_SCHEDULE: ${LIBRENMS_WEATHERMAP_SCHEDULE:-*/5 * * * *}

      DB_HOST: ${DB_HOST:-librenms-mariadb}
      DB_PORT: ${DB_PORT:-3306}

      DB_NAME: ${DB_NAME:-librenms}
      DB_USER: ${DB_USER:-librenms}
      DB_PASSWORD_FILE: /run/secrets/librenms_db_pass

      DB_TIMEOUT: ${DB_TIMEOUT:-60}
    volumes:
      - data:/data
      - cron:/var/spool/cron
    tmpfs:
      - /tmp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.lo.rp_filter=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      default: {}
      proxy: {}
    healthcheck:
      disable: true

  ##############################################################################
  ##############################################################################
  ##############################################################################
  dispatcher:
    image: librenms/librenms:${VERSION_LIBRENMS:-26.8.2}
    <<: *basic
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - FOWNER
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    deploy:
      <<: *basic-deploy
    secrets:
      - librenms_db_pass
    environment:
      TZ: ${TZ:-Europe/Berlin}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}

      LISTEN_IPV6: ${LISTEN_IPV6:-false}
      LIBRENMS_SNMP_COMMUNITY: ${LIBRENMS_SNMP_COMMUNITY:-}

      MEMORY_LIMIT: ${MEMORY_LIMIT:-256M}
      MAX_INPUT_VARS: ${MAX_INPUT_VARS:-1000}
      UPLOAD_MAX_SIZE: ${UPLOAD_MAX_SIZE:-16M}
      OPCACHE_MEM_SIZE: ${OPCACHE_MEM_SIZE:-128}
      REAL_IP_FROM: ${REAL_IP_FROM:-0.0.0.0/32}
      REAL_IP_HEADER: ${REAL_IP_HEADER:-X-Forwarded-For}
      LOG_IP_VAR: ${LOG_IP_VAR:-http_x_forwarded_for}

      CACHE_DRIVER: ${CACHE_DRIVER:-redis}
      SESSION_DRIVER: ${SESSION_DRIVER:-redis}
      REDIS_HOST: valkey

      LIBRENMS_WEATHERMAP: ${LIBRENMS_WEATHERMAP:-false}
      LIBRENMS_WEATHERMAP_SCHEDULE: ${LIBRENMS_WEATHERMAP_SCHEDULE:-*/5 * * * *}

      DB_HOST: ${DB_HOST:-librenms-mariadb}
      DB_PORT: ${DB_PORT:-3306}

      DB_NAME: ${DB_NAME:-librenms}
      DB_USER: ${DB_USER:-librenms}
      DB_PASSWORD_FILE: /run/secrets/librenms_db_pass

      DB_TIMEOUT: ${DB_TIMEOUT:-60}

      DISPATCHER_NODE_ID: ${DISPATCHER_NODE_ID:-dispatcher1}
      SIDECAR_DISPATCHER: ${SIDECAR_DISPATCHER:-1}
    volumes:
      - data:/data
    tmpfs:
      - /tmp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.lo.rp_filter=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      default: {}
    healthcheck:
      disable: true

  ##############################################################################
  ##############################################################################
  ##############################################################################
  librenms-mariadb:
    # https://hub.docker.com/_/mariadb
    image: mariadb:${VERSION_MARIADB:-13.0.2}
    <<: *basic
    cap_add:
      - SETUID
      - SETGID
      - DAC_OVERRIDE
    deploy:
      <<: *basic-deploy
      resources:
        limits:
          cpus: ${RESOURCES_LIMITS_CPUS_MARIADB:-1}
          memory: ${RESOURCES_LIMITS_MEMORY_MARIADB:-1g}
        reservations:
          cpus: ${RESOURCES_RESERVATIONS_CPUS_MARIADB:-0.001}
          memory: ${RESOURCES_RESERVATIONS_MEMORY_MARIADB:-32m}
    secrets:
      - mariadb_root_password
      - librenms_db_pass
    environment:
      TZ: ${TZ:-Europe/Berlin}
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      MARIADB_ROOT_HOST: localhost
      MARIADB_DATABASE: ${DB_NAME:-librenms}
      MARIADB_USER: ${DB_USER:-librenms}
      MARIADB_PASSWORD_FILE: /run/secrets/librenms_db_pass
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - db:/var/lib/mysql
    command:
      - --skip-log-bin
      - --max-allowed-packet=128M
      - --innodb-log-file-size=128M
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 300s
      interval: 30s
      timeout: 5s
      retries: 3

  ##############################################################################
  ##############################################################################
  ##############################################################################
  valkey:
    # https://hub.docker.com/r/valkey/valkey
    image: valkey/valkey:${VERSION_VALKEY:-9.1.2-alpine}
    <<: *basic
    deploy:
      <<: *basic-deploy
      resources:
        limits:
          cpus: ${RESOURCES_LIMITS_CPUS_VALKEY:-1}
          memory: ${RESOURCES_LIMITS_MEMORY_VALKEY:-128m}
        reservations:
          cpus: ${RESOURCES_RESERVATIONS_CPUS_VALKEY:-0.001}
          memory: ${RESOURCES_RESERVATIONS_MEMORY_VALKEY:-32m}
    cap_add:
      - SETUID
      - SETGID
    environment:
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-true}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - valkey:/data
    command: --port 6379 --save 300 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 3

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-overlay}
    attachable: true
    driver_opts:
      encrypted: "true"
  proxy:
    external: true

volumes:
  data: {}
  cron: {}
  db: {}
  valkey: {}

secrets:
  librenms_db_pass:
    file: config/secrets/librenms_db_pass.txt
  mariadb_root_password:
    file: config/secrets/mariadb_root_password.txt
