version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  prometheus:
    image: prom/prometheus:${VERSION:-latest}
    env_file: .env
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          # - "node.id==${NODE_ID}"
          - "node.role==${NODE_ROLE:-manager}"
      restart_policy:
        condition: on-failure
    ports:
      - target: 9090
        published: ${PORT:-9090}
        protocol: tcp
        mode: host
    # environment:
    #   VAR: ...
    configs:
      - source: prom_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - prometheus-data:/prometheus
      - prometheus-conf:/etc/prometheus
    command:
      - --storage.tsdb.retention.time=30d
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      default: {}
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
#
volumes:
  prometheus-data: {}
  prometheus-conf: {}
#
configs:
  prom_config:
    file: $PWD/config/prometheus.yml
