---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.swarm.lbswarm=${LB_SWARM:-true}
    - traefik.swarm.network=proxy

    - traefik.http.routers.netbootxyz.entrypoints=https
    - traefik.http.routers.netbootxyz.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.netbootxyz.tls=true
    - traefik.http.routers.netbootxyz.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.netbootxyz.service=netbootxyz
    - traefik.http.services.netbootxyz.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.netbootxyz.loadbalancer.server.port=${PORT:-3000}

    - traefik.http.routers.netbootxyz_assets.entrypoints=https
    - traefik.http.routers.netbootxyz_assets.rule=Host(`${DOMAIN_ASSETS?domain variable not set}`)
    - traefik.http.routers.netbootxyz_assets.tls=true
    - traefik.http.routers.netbootxyz_assets.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.netbootxyz_assets.service=netbootxyz_assets
    - traefik.http.services.netbootxyz_assets.loadbalancer.server.scheme=${PROTOCOL_ASSETS:-http}
    - traefik.http.services.netbootxyz_assets.loadbalancer.server.port=${PORT_ASSETS:-80}

    # - traefik.udp.routers.mqtt.entrypoints=tftp
    # # - traefik.udp.routers.mqtt.rule=HostSNI(`*`)
    # - traefik.udp.services.mqtt.loadbalancer.server.port=69

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: any
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-0.5}
      memory: ${RESOURCES_LIMITS_MEMORY:-500m}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - DAC_READ_SEARCH
    - SETGID
    - SETUID
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  networks:
    proxy: {}
  healthcheck:
    disable: true
  restart: always

################################################################################
################################################################################
################################################################################
services:
  netbootxyz:
    # https://github.com/netbootxyz/docker-netbootxyz/pkgs/container/netbootxyz
    image: ghcr.io/netbootxyz/netbootxyz:${VERSION:-0.7.3-nbxyz3}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    ports:
      - target: ${PORT_TFTP:-69}
        published: ${PORT_TFTP_PUBLISH:-69}
        protocol: udp
        mode: host
      - target: ${PORT_ASSETS:-80}
        published: ${PORT_ASSETS_PUBLISH:-6969}
        protocol: tcp
        mode: host
    environment:
      WEB_APP_PORT: ${PORT:-3000}
      NGINX_PORT: ${PORT_ASSETS:-80}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - config:/config
      - assets:/assets

################################################################################
################################################################################
################################################################################
networks:
  proxy:
    external: true

volumes:
  config:
    # driver: local
    # driver_opts:
    #   type: nfs
    #   o: nfsvers=4.2,addr=${NFS_HOST?nfs host is not defined},rsize=2097152,wsize=2097152,tcp,nconnect=${NFS_NCON:-8}
    #   device: ":${NFS_PATH_CONFIG?nfs path is not defined}"
  assets:
    # driver: local
    # driver_opts:
    #   type: nfs
    #   o: nfsvers=4.2,addr=${NFS_HOST?nfs host is not defined},rsize=2097152,wsize=2097152,tcp,nconnect=${NFS_NCON:-8}
    #   device: ":${NFS_PATH_ASSETS?nfs path is not defined}"
