---
version: "3.8"

################################################################################
################################################################################
################################################################################

x-basic-deploy-labels:
  &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.mysql-gui.entrypoints=https
    - traefik.http.routers.mysql-gui.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.mysql-gui.tls=true
    - traefik.http.routers.mysql-gui.service=mysql-gui
    - traefik.http.services.mysql-gui.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.mysql-gui.loadbalancer.server.port=${PORT:-8080}
    - traefik.http.routers.mysql-gui.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}

x-basic-deploy:
  &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      # cpus: "0.5"
      memory: 100M
    reservations:
      cpus: "0.001"
      memory: 32M

x-basic:
  &basic
  env_file: .env
  cap_drop: [ "ALL" ]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    mysql: {}
    proxy: {}
  tmpfs:
    - /tmp
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql:${VERSION_MYSQL:-8.0.31}
    <<: *basic
    cap_add:
      - SYS_NICE
      - DAC_OVERRIDE
      - CHOWN
      - SETGID
      - SETUID
    deploy:
      <<: *basic-deploy
      resources:
        limits:
          # cpus: "1.5"
          memory: 1G
        reservations:
          cpus: "0.001"
          memory: 32M
    # ports:
    #   - target: ${PORT_MYSQL:-3306}
    #     published: ${PORT_MYSQL_PUBLISH:-3306}
    #     protocol: tcp
    #     mode: host
    secrets:
      - mysql_root_password
    environment:
      TZ: ${TZ:-Europe/Berlin}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER:-root}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - db:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-buffer-pool-size=900M

      - --max_allowed_packet=64M
      - --innodb_buffer_pool_size=500M
      - --innodb_lock_wait_timeout=90
      - --innodb_file_per_table
      - --innodb_flush_log_at_trx_commit=0
      - --innodb_flush_method=O_DIRECT
      - --innodb_redo_log_capacity=1073741824
      - --innodb_log_buffer_size=16M
      - --innodb_io_capacity=100
      - --thread_cache_size=8
      - --thread_stack=256K
      - --max_connections=100
      - --key_buffer_size=4M
      - --read_buffer_size=128K
      - --read_rnd_buffer_size=128K
      - --sort_buffer_size=128K
      - --join_buffer_size=4M

      - --host_cache_size=0
    networks:
      mysql: {}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u $$(echo $$MYSQL_ROOT_USER) -p$$(cat $$MYSQL_ROOT_PASSWORD_FILE) | grep 'mysqld is alive' || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  ##############################################################################
  ##############################################################################
  ##############################################################################
  # phpmyadmin:
  #   # https://hub.docker.com/_/phpmyadmin
  #   image: phpmyadmin:${VERSION_PHPMYADMIN:-5.2.0-apache}
  #   <<: *basic
  #   deploy:
  #     <<: [ *basic-deploy, *basic-deploy-labels ]
  #   # ports:
  #   #   - target: ${PORT:-80}
  #   #     published: ${PORT_PUBLISH:-80}
  #   #     protocol: tcp
  #   #     mode: host
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_PORT: 3306
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro

  ##############################################################################
  ##############################################################################
  ##############################################################################
  adminer:
    # https://hub.docker.com/_/adminer
    image: adminer:${VERSION_ADMINER:-4.8.1-standalone}
    <<: *basic
    deploy:
      <<: [ *basic-deploy, *basic-deploy-labels ]
    # ports:
    #   - target: ${PORT:-8080}
    #     published: ${PORT_PUBLISH:-8080}
    #     protocol: tcp
    #     mode: host
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_PLUGINS: "tables-filter tinymce"
      ADMINER_DESIGN: "hydra"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: php -S 0.0.0.0:8080 -t /var/www/html

################################################################################
################################################################################
################################################################################
networks:
  mysql:
    name: mysql
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
    driver_opts:
      encrypted: "true"
  proxy:
    external: true

volumes:
  db: {}

secrets:
  mysql_root_password:
    file: config/secrets/mysql_root_password.txt
