---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.swarm.lbswarm=${LB_SWARM:-true}
    - traefik.swarm.network=proxy
    - traefik.http.routers.dashy.entrypoints=https
    - traefik.http.routers.dashy.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.dashy.tls=true
    - traefik.http.routers.dashy.service=dashy
    - traefik.http.services.dashy.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.dashy.loadbalancer.server.port=${PORT:-8080}
    - traefik.http.routers.dashy.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      # cpus: "1.5"
      memory: 500M
    reservations:
      cpus: "0.001"
      memory: 32M

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    proxy: {}
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  dashy:
    # https://hub.docker.com/r/lissy93/dashy
    image: lissy93/dashy:${VERSION:-4.7.19}
    <<: *basic
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    environment:
      - NODE_ENV=production
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - conf:/app/user-data
    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck.js"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 3

################################################################################
################################################################################
################################################################################
networks:
  proxy:
    external: true

volumes:
  conf: {}
