version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  paperless:
    image: jonaswinkler/paperless-ng:${VERSION:-latest}
    env_file: .env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==${NODE_ROLE:-manager}"
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=${LB_SWARM:-true}
        - traefik.docker.network=proxy
        - traefik.http.routers.paperless-ng.entrypoints=https
        - traefik.http.routers.paperless-ng.rule=Host(`${DOMAIN?domain variable not set}`)
        - traefik.http.routers.paperless-ng.tls=true
        - traefik.http.routers.paperless-ng.service=paperless-ng
        - traefik.http.services.paperless-ng.loadbalancer.server.scheme=${PROTOCOL:-http}
        - traefik.http.services.paperless-ng.loadbalancer.server.port=${PORT:-8000}
        - traefik.http.routers.paperless-ng.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
      resources:
        limits:
          memory: 1g
    # ports:
    #   - target: 8000
    #     published: ${PORT:-8000}
    #     protocol: tcp
    #     mode: host
    environment:
      PAPERLESS_REDIS: ${REDIS:-redis://redis:6379}
      PAPERLESS_DBHOST: ${PAPERLESS_DBHOST:-postgress}
      PAPERLESS_TIKA_ENABLED: ${TIKA_ENABLED:-1}
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: ${GOTENBERG_ENDPOINT:-http://gotenberg:3000}
      PAPERLESS_TIKA_ENDPOINT: ${TIKA_ENDPOINT:-http://tika:9998}
      PAPERLESS_OCR_LANGUAGES: deu eng
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_TIME_ZONE: Europe/Berlin
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      # - $PWD/export:/usr/src/paperless/export
      # - $PWD/consume:/usr/src/paperless/consume
    networks:
      default: {}
      proxy: {}
    healthcheck:
      test: ["CMD", "curl", "-f", "${PROTOCOL:-http}://localhost:${PORT:-8000}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  ##############################################################################
  ##############################################################################
  ##############################################################################
  postgress:
    image: postgres:13
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==${NODE_ROLE:-manager}"
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g
    secrets:
      - postgres_password
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-paperless}
      POSTGRES_USER: ${POSTGRES_USER:-paperless}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - pgdata:/var/lib/postgresql/data
    networks:
      default: {}
    restart: always

  gotenberg:
    image: thecodingmachine/gotenberg
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==${NODE_ROLE:-manager}"
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g
    environment:
      DISABLE_GOOGLE_CHROME: 1
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      default: {}
    restart: always

  tika:
    image: apache/tika
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==${NODE_ROLE:-manager}"
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      default: {}
    restart: always

  redis:
    image: redis:6.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==${NODE_ROLE:-manager}"
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - redis_data:/data
    networks:
      default: {}
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
  proxy:
    external: true

volumes:
  data: {}
  media: {}
  pgdata: {}
  redis_data: {}

secrets:
  postgres_password:
    file: config/secrets/postgres_password.txt
