version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  netbox:
    ports:
    - 8000:8080
