---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.observium.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.observium.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.observium.tls=true
    - traefik.http.routers.observium.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.observium.service=observium
    - traefik.http.services.observium.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.observium.loadbalancer.server.port=${PORT:-80}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-2}
      memory: ${RESOURCES_LIMITS_MEMORY:-2g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: .env
  cap_add:
    - NET_ADMIN
    - NET_RAW
    - NET_BIND_SERVICE
    - NET_BROADCAST
    - DAC_READ_SEARCH
    - DAC_OVERRIDE
    - CHOWN
    - SETUID
    - SETGID
    - SYSLOG
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    default: {}
    proxy: {}
  healthcheck:
    disable: true
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  observium:
    # NOTE: get current version to replace $VERSION
    # wget https://www.observium.org/observium-community-latest.tar.gz \
    # -O /tmp/observium-community-latest.tar.gz \
    # && tar zxf /tmp/observium-community-latest.tar.gz --checkpoint=.1000 -C /tmp \
    # && rm /tmp/observium-community-latest.tar.gz \
    # && cat /tmp/observium/VERSION | tr ' ' '-' | cut -d '-' -f2- | tr '[:upper:]' '[:lower:]' \
    # && rm /tmp/observium -rf
    hostname: observium
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        # VERSION_UBUNTU: "23.10"
        VERSION_DEBIAN: 12.5-slim
        BUILD_DATE: ${BUILD_DATE:-2024}
        VERSION: ${VERSION:-ce-23.9}
    image: mvladislav/observium:${VERSION:-ce-23.9}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    # ports:
    #   - target: ${PORT:-80}
    #     published: ${PORT_PUBLISH:-80}
    #     protocol: tcp
    #     mode: host
    #   - target: 514
    #     published: 514
    #     protocol: udp
    #     mode: host
    secrets:
      - observium_admin_pass
      - mariadb_user_password
    environment:
      TZ: ${TZ:-Europe/Berlin}

      OBSERVIUM_ADMIN_USER: ${OBSERVIUM_ADMIN_USER:-admin}
      OBSERVIUM_ADMIN_PASS_FILE: /run/secrets/observium_admin_pass
      OBSERVIUM_BASE_URL: https://${DOMAIN?domain variable not set}

      OBSERVIUM_DB_NAME: ${MARIADB_DATABASE:-observium}
      OBSERVIUM_DB_USER: ${MARIADB_USER:-observium}
      OBSERVIUM_DB_PASS_FILE: /run/secrets/mariadb_user_password

      OBSERVIUM_DB_HOST: ${MARIADB_HOST:-mariadb}
      OBSERVIUM_DB_PORT: ${MARIADB_PORT:-3306}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - logs_observium:/opt/observium/logs
      - logs_sys:/var/log
      - rrd:/opt/observium/rrd
      # - html:/opt/observium/html
    healthcheck:
      test: ["CMD", "curl", "-f", "${PROTOCOL:-http}://localhost:${PORT:-80}"]
      interval: 30s
      timeout: 10s
      retries: 5

  ##############################################################################
  ##############################################################################
  ##############################################################################
  mariadb:
    # https://hub.docker.com/_/mariadb
    image: mariadb:${VERSION_MARIADB:-11.3.2}
    <<: *basic
    deploy:
      <<: *basic-deploy
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    secrets:
      - mariadb_user_password
    environment:
      TZ: ${TZ:-Europe/Berlin}

      MARIADB_DATABASE: ${MARIADB_DATABASE:-observium}
      MARIADB_USER: ${MARIADB_USER:-observium}
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_user_password
      MARIADB_RANDOM_ROOT_PASSWORD: ${MARIADB_RANDOM_ROOT_PASSWORD:-true}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - db:/var/lib/mysql
    command:
      - --log-bin=mysql-bin
      - --expire-logs-days=7
    networks:
      default: {}
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh --no-defaults"]
      start_period: 5s
      interval: 10s
      retries: 5
      timeout: 3s

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
    driver_opts:
      encrypted: "true"
  proxy:
    external: true

volumes:
  logs_observium: {}
  logs_sys: {}
  rrd: {}
  # html: {}
  db: {}

secrets:
  observium_admin_pass:
    file: config/secrets/observium_admin_pass.txt
  mariadb_user_password:
    file: config/secrets/mariadb_user_password.txt
  mariadb_root_password:
    file: config/secrets/mariadb_root_password.txt
