---
version: "3.8"

################################################################################
################################################################################
################################################################################

x-basic-deploy-labels:
  &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.observium.entrypoints=https
    - traefik.http.routers.observium.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.observium.tls=true
    - traefik.http.routers.observium.service=observium
    - traefik.http.services.observium.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.observium.loadbalancer.server.port=${PORT:-80}
    - traefik.http.routers.observium.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}

x-basic-deploy:
  &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      # cpus: "1.5"
      memory: 1g
    reservations:
      cpus: "0.001"
      memory: 50M

x-basic:
  &basic
  env_file: .env
  cap_add:
    - NET_ADMIN
    - NET_RAW
    - NET_BIND_SERVICE
    - NET_BROADCAST
    - DAC_READ_SEARCH
    - DAC_OVERRIDE
    - CHOWN
    - SETUID
    - SETGID
    - SYSLOG
  cap_drop: [ "ALL" ]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
      default: {}
      proxy: {}
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  observium:
    # NOTE: get current version to replace $VERSION
    # wget https://www.observium.org/observium-community-latest.tar.gz \
    # -O /tmp/observium-community-latest.tar.gz \
    # && tar zxf /tmp/observium-community-latest.tar.gz --checkpoint=.1000 -C /tmp \
    # && rm /tmp/observium-community-latest.tar.gz \
    # && cat /tmp/observium/VERSION | tr ' ' '-' | cut -d '-' -f2- | tr '[:upper:]' '[:lower:]' \
    # && rm /tmp/observium -rf
    hostname: observium
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VERSION_DEBIAN: 11.6-slim
        BUILD_DATE: ${BUILD_DATE:-2023}
        VERSION: ${VERSION:-ce-23.1}
    image: mvladislav/observium:${VERSION:-ce-23.1}
    <<: *basic
    deploy:
      <<: [ *basic-deploy, *basic-deploy-labels ]
    # ports:
    #   # - target: 80
    #   #   published: ${PORT:-80}
    #   #   protocol: tcp
    #   #   mode: host
    #   - target: 514
    #     published: 514
    #     protocol: udp
    #     mode: host
    secrets:
      - observium_admin_pass
      - observium_db_pass
    environment:
      TZ: ${TZ:-Europe/Berlin}

      OBSERVIUM_ADMIN_USER: ${OBSERVIUM_ADMIN_USER:-groot}
      OBSERVIUM_ADMIN_PASS_FILE: /run/secrets/observium_admin_pass
      OBSERVIUM_BASE_URL: https://${DOMAIN?domain variable not set}

      OBSERVIUM_DB_HOST: ${OBSERVIUM_DB_HOST:-observium-mariadb}
      OBSERVIUM_DB_PORT: ${OBSERVIUM_DB_PORT:-3306}

      OBSERVIUM_DB_NAME: ${OBSERVIUM_DB_NAME:-observium}
      OBSERVIUM_DB_USER: ${OBSERVIUM_DB_USER:-observium}
      OBSERVIUM_DB_PASS_FILE: /run/secrets/observium_db_pass
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - logs_observium:/opt/observium/logs
      - logs_sys:/var/log
      - rrd:/opt/observium/rrd
      # - html:/opt/observium/html
    tmpfs:
      - /tmp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.lo.rp_filter=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=0
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "${PROTOCOL:-http}://localhost:${PORT:-80}"
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  ##############################################################################
  ##############################################################################
  ##############################################################################
  observium-mariadb:
    # https://hub.docker.com/_/mariadb
    image: mariadb:${VERSION_MARIADB:-10.7.8}
    <<: *basic
    deploy:
      <<: *basic-deploy
    cap_add:
      - SYS_NICE
      - DAC_OVERRIDE
      - CHOWN
      - SETGID
      - SETUID
    secrets:
      - mariadb_root_password
      - observium_db_pass
    environment:
      TZ: ${TZ:-Europe/Berlin}
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      MARIADB_DATABASE: ${OBSERVIUM_DB_NAME:-observium}
      MARIADB_USER: ${OBSERVIUM_DB_USER:-observium}
      MARIADB_PASSWORD_FILE: /run/secrets/observium_db_pass
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - db:/var/lib/mysql
    command:
      - --log-bin=mysql-bin
      - --expire-logs-days=7
    networks:
      default: {}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -P 3306 -u root -p$$(cat $$MARIADB_ROOT_PASSWORD_FILE) | grep 'mysqld is alive' || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  ##############################################################################
  ##############################################################################
  ##############################################################################
  # phpmyadmin:
  #   # https://hub.docker.com/_/phpmyadmin
  #   image: phpmyadmin:${VERSION_PHPMYADMIN:-5.2.0-apache}
  #   <<: *basic
  #   deploy:
  #     <<: *basic-deploy
  #     labels:
  #       - traefik.enable=true
  #       - traefik.docker.lbswarm=${LB_SWARM:-true}
  #       - traefik.docker.network=proxy
  #       - traefik.http.routers.phpmyadmin.entrypoints=https
  #       - traefik.http.routers.phpmyadmin.rule=Host(`${DOMAIN_PHPMYADMIN?domain variable not set}`)
  #       - traefik.http.routers.phpmyadmin.tls=true
  #       - traefik.http.routers.phpmyadmin.service=phpmyadmin
  #       - traefik.http.services.phpmyadmin.loadbalancer.server.scheme=${PROTOCOL_PHPMYADMIN:-http}
  #       - traefik.http.services.phpmyadmin.loadbalancer.server.port=${PORT_PHPMYADMIN:-8080}
  #       - traefik.http.routers.phpmyadmin.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
  #   # ports:
  #   #   - target: ${PORT:-8080}
  #   #     published: ${PORT_PUBLISH:-8080}
  #   #     protocol: tcp
  #   #     mode: host
  #   environment:
  #     PMA_HOST: observium-mariadb
  #     PMA_PORT: 3306
  #     UPLOAD_LIMIT: 5G
  #     APACHE_PORT: 8080
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
    driver_opts:
      encrypted: "true"
  proxy:
    external: true

volumes:
  logs_observium: {}
  logs_sys: {}
  rrd: {}
  # html: {}
  db: {}

secrets:
  observium_admin_pass:
    file: config/secrets/observium_admin_pass.txt
  observium_db_pass:
    file: config/secrets/observium_db_pass.txt
  mariadb_root_password:
    file: config/secrets/mariadb_root_password.txt
