---
version: "3.8"

################################################################################
################################################################################
################################################################################

x-basic-deploy-labels:
  &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.observium.entrypoints=https
    - traefik.http.routers.observium.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.observium.tls=true
    - traefik.http.routers.observium.service=observium
    - traefik.http.services.observium.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.observium.loadbalancer.server.port=${PORT:-80}
    - traefik.http.routers.observium.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}

x-basic-deploy:
  &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      # cpus: "1.5"
      memory: 2g
    reservations:
      cpus: "0.001"
      memory: 50M

x-basic:
  &basic
  env_file: .env
  cap_add:
    - NET_BIND_SERVICE
    - NET_BROADCAST
    - DAC_READ_SEARCH
    - DAC_OVERRIDE
    - CHOWN
    - SETUID
    - SETGID
    - SYSLOG
  cap_drop: [ "ALL" ]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    mysql: {}
    proxy: {}
  tmpfs:
    - /tmp
  sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.src_valid_mark=1
    - net.ipv4.conf.all.rp_filter=0
    - net.ipv4.conf.default.rp_filter=0
    - net.ipv4.conf.eth0.rp_filter=0
    - net.ipv4.conf.lo.rp_filter=0
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.all.disable_ipv6=0
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  observium:
    hostname: observium
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VERSION_DEBIAN: 11.6-slim
        BUILD_DATE: ${BUILD_DATE:-2023}
        VERSION: ${VERSION:-ce-22.12.12447}
    image: mvladislav/observium:${VERSION:-ce-22.12.12447}
    <<: *basic
    deploy:
      <<: [ *basic-deploy, *basic-deploy-labels ]
    # ports:
    #   # - target: 80
    #   #   published: ${PORT:-80}
    #   #   protocol: tcp
    #   #   mode: host
    #   - target: 514
    #     published: 514
    #     protocol: udp
    #     mode: host
    secrets:
      - observium_admin_pass
      - observium_db_pass
    environment:
      TZ: ${TZ:-Europe/Berlin}

      OBSERVIUM_ADMIN_USER: ${OBSERVIUM_ADMIN_USER:-groot}
      OBSERVIUM_ADMIN_PASS_FILE: /run/secrets/observium_admin_pass
      OBSERVIUM_BASE_URL: https://${DOMAIN?domain variable not set}

      OBSERVIUM_DB_HOST: ${OBSERVIUM_DB_HOST:-mysql}
      OBSERVIUM_DB_PORT: ${OBSERVIUM_DB_PORT:-3306}

      OBSERVIUM_DB_NAME: ${OBSERVIUM_DB_NAME:-observium}
      OBSERVIUM_DB_USER: ${OBSERVIUM_DB_USER:-observium}
      OBSERVIUM_DB_PASS_FILE: /run/secrets/observium_db_pass
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - logs_observium:/opt/observium/logs
      - logs_sys:/var/log
      - rrd:/opt/observium/rrd
      # - html:/opt/observium/html
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "${PROTOCOL:-http}://localhost:${PORT:-80}"
        ]
      interval: 30s
      timeout: 10s
      retries: 5

################################################################################
################################################################################
################################################################################
networks:
  mysql:
    external: true
  proxy:
    external: true

volumes:
  logs_observium: {}
  logs_sys: {}
  rrd: {}
  # html: {}

secrets:
  observium_admin_pass:
    file: config/secrets/observium_admin_pass.txt
  observium_db_pass:
    file: config/secrets/observium_db_pass.txt
