---
x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: any
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-0.5}
      memory: ${RESOURCES_LIMITS_MEMORY:-250m}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges=true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  healthcheck:
    disable: true
  tmpfs:
    - /tmp
  restart: always

################################################################################
################################################################################
################################################################################
services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  diun:
    # https://github.com/crazy-max/diun/pkgs/container/diun
    image: ghcr.io/crazy-max/diun:${VERSION:-4.29}
    <<: *basic
    deploy:
      <<: *basic-deploy
    environment:
      TZ: ${TZ:-Europe/Berlin}

      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_JSON: ${LOG_JSON:-false}

      DIUN_WATCH_WORKERS: ${DIUN_WATCH_WORKERS:-20}
      DIUN_WATCH_SCHEDULE: ${DIUN_WATCH_SCHEDULE:-0 */6 * * *}
      DIUN_WATCH_JITTER: ${DIUN_WATCH_JITTER:-30s}

      DIUN_PROVIDERS_DOCKER: ${DIUN_PROVIDERS_DOCKER:-false}
      DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT: ${DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT:-false}
      DIUN_PROVIDERS_SWARM: ${DIUN_PROVIDERS_SWARM:-true}
      DIUN_PROVIDERS_SWARM_WATCHBYDEFAULT: ${DIUN_PROVIDERS_SWARM_WATCHBYDEFAULT:-true}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/data
    command: >
      serve

################################################################################
################################################################################
################################################################################

volumes:
  data: {}
