serversTransport:
  insecureSkipVerify: false
  rootCAs:
    - "/etc/traefik/certs/ca.pem"

################################################################
# TLS
################################################################

# Configure your CertificateResolver here...
# ---
# certificatesResolvers:
#   staging:
#     acme:
#       email: your-email@example.com
#       storage: /etc/traefik/certs/acme.json
#       caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
#       tlschallenge: true
#       httpChallenge:
#         entryPoint: web
#
#   production:
#     acme:
#       email: your-email@example.com
#       storage: /etc/traefik/certs/acme.json
#       caServer: "https://acme-v02.api.letsencrypt.org/directory"
#       dnsChallenge:
#         provider: "cloudflare"
#         delayBeforeCheck: 0
#       httpChallenge:
#         entryPoint: web

# (Optional) Overwrite Default Certificates
tls:
  certificates:
    - certFile: /etc/traefik/certs/cert.pem
      keyFile: /etc/traefik/certs/cert-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/cert.pem
        keyFile: /etc/traefik/certs/cert-key.pem
