---
################################################################
#
# Configuration sample for Traefik v3.
# Schema: https://json.schemastore.org/traefik-v2-file-provider.json
#
# For Traefik v3: https://github.com/traefik/traefik/blob/v3.0/traefik.sample.yml
#
################################################################

################################################################
# TLS
################################################################

# (Optional) Overwrite Default Certificates
tls:
  certificates:
    - certFile: /etc/traefik/certs/cert.pem
      keyFile: /etc/traefik/certs/cert-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/cert.pem
        keyFile: /etc/traefik/certs/cert-key.pem
