---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.swarm.lbswarm=${LB_SWARM:-true}
    - traefik.swarm.network=proxy
    - traefik.http.routers.gotify.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.gotify.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.gotify.tls=true
    - traefik.http.routers.gotify.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.gotify.service=gotify
    - traefik.http.services.gotify.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.gotify.loadbalancer.server.port=${PORT:-80}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: any
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-1}
      memory: ${RESOURCES_LIMITS_MEMORY:-500m}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  networks:
    proxy: {}
  healthcheck:
    disable: true
  restart: always

################################################################################
################################################################################
################################################################################
services:
  # https://hub.docker.com/r/gotify/server
  gotify:
    image: gotify/server:${VERSION:-2.6.1}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    environment:
      GOTIFY_SERVER_PORT: ${PORT:-80}
      GOTIFY_DEFAULTUSER_NAME: ${GOTIFY_DEFAULTUSER_NAME:-groot}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/app/data

################################################################################
################################################################################
################################################################################
networks:
  proxy:
    external: true

volumes:
  data: {}
