version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  cloudflare_ddns:
    image: oznu/cloudflare-ddns:${VERSION:-latest}
    env_file: .env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==${NODE_ROLE:-manager}"
      restart_policy:
        condition: on-failure
    environment:
      # API KEY only input in .env
      # API_KEY: ${API_KEY}
      ZONE: ${ZONE}
      PROXIED: ${PROXIED:-true}
      RRTYPE: ${RRTYPE:-A}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      default: {}
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
