---
version: "3.8"

################################################################################
################################################################################
################################################################################

x-basic-deploy-labels:
  &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.mariadb-gui.entrypoints=https
    - traefik.http.routers.mariadb-gui.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.mariadb-gui.tls=true
    - traefik.http.routers.mariadb-gui.service=mariadb-gui
    - traefik.http.services.mariadb-gui.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.mariadb-gui.loadbalancer.server.port=${PORT:-8080}
    - traefik.http.routers.mariadb-gui.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}

x-basic-deploy:
  &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      # cpus: "0.5"
      memory: 100M
    reservations:
      cpus: "0.001"
      memory: 32M

x-basic:
  &basic
  env_file: .env
  cap_drop: [ "ALL" ]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    mysql: {}
    proxy: {}
  tmpfs:
    - /tmp
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  mariadb:
    # https://hub.docker.com/_/mariadb
    image: mariadb:${VERSION_MARIADB:-10.7.8}
    <<: *basic
    cap_add:
      - SYS_NICE
      - DAC_OVERRIDE
      - CHOWN
      - SETGID
      - SETUID
    deploy:
      <<: *basic-deploy
      resources:
        limits:
          # cpus: "1.5"
          memory: 1G
        reservations:
          cpus: "0.001"
          memory: 32M
    secrets:
      - mariadb_root_password
    environment:
      TZ: ${TZ:-Europe/Berlin}
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - db:/var/lib/mysql
    command:
      - --log-bin=mysql-bin
      - --expire-logs-days=7
    networks:
      default: {}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -P 3306 -u root -p$$(cat $$MARIADB_ROOT_PASSWORD_FILE) | grep 'mysqld is alive' || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  ##############################################################################
  ##############################################################################
  ##############################################################################
  # phpmyadmin:
  #   # https://hub.docker.com/_/phpmyadmin
  #   image: phpmyadmin:${VERSION_PHPMYADMIN:-5.2.0-apache}
  #   <<: *basic
  #   deploy:
  #     <<: [ *basic-deploy, *basic-deploy-labels ]
  #   # ports:
  #   #   - target: ${PORT:-80}
  #   #     published: ${PORT_PUBLISH:-80}
  #   #     protocol: tcp
  #   #     mode: host
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_PORT: 3306
  #     UPLOAD_LIMIT: 1G
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro

  ##############################################################################
  ##############################################################################
  ##############################################################################
  adminer:
    # https://hub.docker.com/_/adminer
    image: adminer:${VERSION_ADMINER:-4.8.1-standalone}
    <<: *basic
    deploy:
      <<: [ *basic-deploy, *basic-deploy-labels ]
    # ports:
    #   - target: ${PORT:-8080}
    #     published: ${PORT_PUBLISH:-8080}
    #     protocol: tcp
    #     mode: host
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_PLUGINS: "tables-filter tinymce file-upload"
      ADMINER_DESIGN: "hydra"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: php -S 0.0.0.0:8080 -t /var/www/html

################################################################################
################################################################################
################################################################################
networks:
  mariadb:
    name: mariadb
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
    driver_opts:
      encrypted: "true"
  proxy:
    external: true

volumes:
  db: {}

secrets:
  mariadb_root_password:
    file: config/secrets/mariadb_root_password.txt
