---
version: "3.8"

################################################################################
################################################################################
################################################################################

x-basic-deploy-labels:
  &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.gophish-admin.entrypoints=https
    - traefik.http.routers.gophish-admin.rule=Host(`${DOMAIN_ADMIN?domain admin variable not set}`)
    - traefik.http.routers.gophish-admin.tls=true
    - traefik.http.routers.gophish-admin.service=gophish-admin
    - traefik.http.services.gophish-admin.loadbalancer.server.scheme=${PROTOCOL_ADMIN:-http}
    - traefik.http.services.gophish-admin.loadbalancer.server.port=${PORT_ADMIN:-3333}
    - traefik.http.routers.gophish-admin.middlewares=${MIDDLEWARE_SECURED_ADMIN:-default-secured@file}

    - traefik.http.routers.gophish-phish.entrypoints=https
    - traefik.http.routers.gophish-phish.rule=${DOMAINS_PHISH?domains phishing variable not set}
    - traefik.http.routers.gophish-phish.tls=true
    - traefik.http.routers.gophish-phish.service=gophish-phish
    - traefik.http.services.gophish-phish.loadbalancer.server.scheme=${PROTOCOL_PHISH:-http}
    - traefik.http.services.gophish-phish.loadbalancer.server.port=${PORT_PHISH:-80}
    - traefik.http.routers.gophish-phish.middlewares=${MIDDLEWARE_SECURED_PHISH:-default-secured@file}

x-basic-deploy:
  &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      cpus: "1.5"
      memory: 1g # 500M
    reservations:
      cpus: "0.001"
      memory: 32M

x-basic:
  &basic
  env_file: .env
  cap_add:
    - NET_BIND_SERVICE
  cap_drop: [ "ALL" ]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  tmpfs:
    - /tmp
  sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.src_valid_mark=1
    - net.ipv4.conf.all.rp_filter=0
    - net.ipv4.conf.default.rp_filter=0
    - net.ipv4.conf.eth0.rp_filter=0
    - net.ipv4.conf.lo.rp_filter=0
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.all.disable_ipv6=0
  networks:
    proxy: {}
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  gophish:
    # https://hub.docker.com/r/gophish/gophish
    image: gophish/gophish:${VERSION:-0.12.1}
    <<: *basic
    deploy:
      <<: [ *basic-deploy, *basic-deploy-labels ]
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/opt/gophish
      # - data:/app/database
      - app_endpoint:/app/static/endpoint
      - opt_endpoint:/opt/gophish/static/endpoint
    environment:
      ADMIN_LISTEN_URL: ${ADMIN_LISTEN_URL:-0.0.0.0:${PORT_ADMIN:-3333}}
      ADMIN_USE_TLS: ${ADMIN_USE_TLS:-false}
      PHISH_LISTEN_URL: ${PHISH_LISTEN_URL:-0.0.0.0:${PORT_PHISH:-80}}
      PHISH_USE_TLS: ${PHISH_USE_TLS:-false}
      ADMIN_TRUSTED_ORIGINS: ${DOMAIN_ADMIN?domain admin variable not set}
      # DB_FILE_PATH: /app/database/gophish.db
    healthcheck:
      disable: true

################################################################################
################################################################################
################################################################################
networks:
  proxy:
    external: true

volumes:
  data: {}
  app_endpoint: {}
  opt_endpoint: {}
