---
x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: any
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-4}
      memory: ${RESOURCES_LIMITS_MEMORY:-2g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  # cap_add: ["ALL"]
  # cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges=true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  healthcheck:
    disable: true
  restart: always

################################################################################
################################################################################
################################################################################
services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  pangolin:
    # https://hub.docker.com/r/fosrl/pangolin
    image: fosrl/pangolin:${VERSION_PANGOLIN:-1.5.1}
    <<: *basic
    deploy:
      <<: *basic-deploy
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_VOLUME:-$PWD}/config/pangolin:/app/config
    environment:
      # APP
      APP_BASEDOMAIN: https://${DASHBOARDURL?domain variable not set}
      # DOMAINS
      DOMAINS_DEFAULT_BASEDOMAIN: ${BASEDOMAIN?base domain variable not set}
      DOMAINS_DEFAULT_CERTRESOLVER: letsencrypt
      DOMAINS_DEFAULT_PREFERWILDCARDCERT: "true"
      # GERBIL
      GERBIL_BASEENDPOINT: ${BASEDOMAIN?base domain variable not set}
      # USER
      USERS_SERVERADMIN_EMAIL: ${USERS_SERVERADMIN_EMAIL?you need set username}
      USERS_SERVERADMIN_PASSWORD: ${USERS_SERVERADMIN_PASSWORD?you need set user password}
      GENERATE_TRAEFIK_CONFIG: "false"
      # FLAGS
      FLAGS_EMAIL_VERIFICATION_REQUIRED: "false"
      FLAGS_DISABLE_SIGNUP_WITHOUT_INVITE: "true"
      FLAGS_DISABLE_USER_CREATE_ORG: "true"
      FLAGS_ALLOW_RAW_RESOURCES: "true"
      FLAGS_ALLOW_BASE_DOMAIN_RESOURCES: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      start_period: 10s
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      pangolin: {}

  ##############################################################################
  ##############################################################################
  ##############################################################################
  gerbil:
    # https://hub.docker.com/r/fosrl/gerbil
    image: fosrl/gerbil:${VERSION_GERBIL:-1.0.0}
    depends_on:
      pangolin:
        condition: service_healthy
    <<: *basic
    deploy:
      <<: *basic-deploy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 443:443 # Port for traefik because of the network_mode
      - 80:80 # Port for traefik because of the network_mode
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_VOLUME:-$PWD}/config/pangolin:/var/config
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -kIf http://127.0.0.1:3003 > /dev/null 2>&1 || exit 1",
        ]
      start_period: 10s
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      pangolin: {}

  ##############################################################################
  ##############################################################################
  ##############################################################################
  traefik:
    # https://hub.docker.com/_/traefik
    image: traefik:${VERSION_TRAEFIK:-v3.4.1}
    depends_on:
      pangolin:
        condition: service_healthy
    <<: *basic
    deploy:
      <<: *basic-deploy
    secrets:
      - traefik_basicauth_secret
      - ionos_api_key_secret
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_VOLUME:-$PWD}/config/pangolin/traefik:/etc/traefik:ro
      - ${PATH_VOLUME:-$PWD}/config/pangolin/letsencrypt:/letsencrypt
    environment:
      IONOS_API_KEY_FILE: /run/secrets/ionos_api_key_secret
      # https://doc.traefik.io/traefik/reference/static-configuration/env/
      # Global configuration
      TRAEFIK_GLOBAL_CHECKNEWVERSION: ${TRAEFIK_GLOBAL_CHECKNEWVERSION:-true}
      TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE: "false"
      # EntryPoints configuration
      TRAEFIK_ENTRYPOINTS_WEB: "true"
      TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: ":80"
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO: websecure
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME: https
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_PERMANENT: "true"
      TRAEFIK_ENTRYPOINTS_WEBSECURE: "true"
      TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: ":443"
      TRAEFIK_ENTRYPOINTS_WEBSECURE_TRANSPORT_RESPONDINGTIMEOUTS_READTIMEOUT: 30m
      TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_CERTRESOLVER: letsencrypt
      # Traefik logs configuration
      TRAEFIK_LOG: ${TRAEFIK_LOG:-true}
      TRAEFIK_LOG_LEVEL: INFO # TRACE, DEBUG, PANIC, FATAL, ERROR, WARN, INFO
      TRAEFIK_LOG_FORMAT: common
      # Access logs configuration
      TRAEFIK_ACCESSLOG: ${TRAEFIK_ACCESSLOG:-true}
      TRAEFIK_ACCESSLOG_FORMAT: common
      TRAEFIK_ACCESSLOG_FIELDS_DEFAULTMODE: keep
      TRAEFIK_ACCESSLOG_FIELDS_NAMES_CLIENTUSERNAME: drop
      TRAEFIK_ACCESSLOG_FIELDS_HEADERS_DEFAULTMODE: keep
      TRAEFIK_ACCESSLOG_FIELDS_HEADERS_NAMES_USER-Agent: keep
      TRAEFIK_ACCESSLOG_FIELDS_HEADERS_NAMES_AUTHORIZATION: drop
      TRAEFIK_ACCESSLOG_FIELDS_HEADERS_NAMES_CONTENT-Type: keep
      # API and dashboard configuration
      TRAEFIK_API: ${TRAEFIK_API:-true}
      TRAEFIK_API_DASHBOARD: ${TRAEFIK_API_DASHBOARD:-true}
      TRAEFIK_API_INSECURE: "false"
      TRAEFIK_API_DEBUG: "false"
      # Ping configuration
      TRAEFIK_PING: "true"
      # Docker configuration backend
      TRAEFIK_PROVIDERS_HTTP: "true"
      TRAEFIK_PROVIDERS_HTTP_ENDPOINT: http://pangolin:3001/api/v1/traefik-config
      TRAEFIK_PROVIDERS_HTTP_POLLINTERVAL: 5s
      TRAEFIK_PROVIDERS_FILE_FILENAME: /etc/traefik/dynamic_config.yml
      # TLS
      TRAEFIK_SERVERSTRANSPORT_INSECURESKIPVERIFY: "true"
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT: "true"
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL: ${ACME_EMAIL?ACME Mail not set}
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_STORAGE: /letsencrypt/acme.json
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_KEYTYPE: EC256
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_CASERVER: ${ACME_CASERVER:-https://acme-staging-v02.api.letsencrypt.org/directory} # https://acme-v02.api.letsencrypt.org/directory
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_DNSCHALLENGE: "true"
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_DNSCHALLENGE_PROVIDER: ${ACME_DNSCHALLENGE_PROVIDER:-ionos}
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_DNSCHALLENGE_RESOLVERS: ${ACME_DNSCHALLENGE_RESOLVERS:-9.9.9.9,194.242.2.2,1.1.1.1}
      # PLUGINS
      TRAEFIK_EXPERIMENTAL_PLUGINS_BADGER_MODULENAME: github.com/fosrl/badger
      TRAEFIK_EXPERIMENTAL_PLUGINS_BADGER_VERSION: ${VERSION_BADGER:-v1.2.0}
    healthcheck:
      test: "traefik healthcheck --ping"
      start_period: 5s
      interval: 10s
      retries: 5
      timeout: 3s
    network_mode: service:gerbil # Ports appear on the gerbil service

################################################################################
################################################################################
################################################################################
networks:
  pangolin:
    name: pangolin
    driver: ${NETWORK_MODE:-overlay}
    attachable: true
    driver_opts:
      encrypted: "true"

secrets:
  traefik_basicauth_secret:
    file: config/secrets/traefik_basicauth_secret.txt
  ionos_api_key_secret:
    file: config/secrets/ionos_api_key_secret.txt
