---
x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: any
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-1}
      memory: ${RESOURCES_LIMITS_MEMORY:-1g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges=true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  healthcheck:
    disable: true
  restart: always

################################################################################
################################################################################
################################################################################
services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  pangolin:
    # https://hub.docker.com/r/fosrl/pangolin
    image: fosrl/pangolin:${VERSION_PANGOLIN:-latest}
    <<: *basic
    deploy:
      <<: *basic-deploy
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_VOLUME:-$PWD}/config/pangolin:/app/config
    environment:
      APP_DASHBOARDURL: https://${DASHBOARDURL?domain variable not set}
      APP_BASEDOMAIN: ${BASEDOMAIN?base domain variable not set}
      GERBIL_BASEENDPOINT: ${BASEDOMAIN?base domain variable not set}
      USERS_SERVERADMIN_EMAIL: ${USERS_SERVERADMIN_EMAIL?you need set username}
      USERS_SERVERADMIN_PASSWORD: ${USERS_SERVERADMIN_PASSWORD?you need set user password}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      start_period: 10s
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      pangolin: {}

  ##############################################################################
  ##############################################################################
  ##############################################################################
  gerbil:
    # https://hub.docker.com/r/fosrl/gerbil
    image: fosrl/gerbil:${VERSION_GERBIL:-latest}
    <<: *basic
    deploy:
      <<: *basic-deploy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 443:443 # Port for traefik because of the network_mode
      - 80:80 # Port for traefik because of the network_mode
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_VOLUME:-$PWD}/config/pangolin:/var/config
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -kIf http://127.0.0.1:3003 > /dev/null 2>&1 || exit 1",
        ]
      start_period: 10s
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      pangolin: {}

  ##############################################################################
  ##############################################################################
  ##############################################################################
  traefik:
    # https://hub.docker.com/_/traefik
    image: traefik:${VERSION_TRAEFIK:-latest}
    <<: *basic
    deploy:
      <<: *basic-deploy
    secrets:
      - traefik_basicauth_secret
      - ionos_api_key_secret
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_VOLUME:-$PWD}/config/pangolin/traefik:/etc/traefik:ro
      - ${PATH_VOLUME:-$PWD}/config/pangolin/letsencrypt:/letsencrypt
    environment:
      IONOS_API_KEY_FILE: /run/secrets/ionos_api_key_secret
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    healthcheck:
      test: "traefik healthcheck --ping"
      start_period: 5s
      interval: 10s
      retries: 5
      timeout: 3s
    network_mode: service:gerbil # Ports appear on the gerbil service

################################################################################
################################################################################
################################################################################
networks:
  pangolin:
    name: pangolin
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
    driver_opts:
      encrypted: "true"

secrets:
  traefik_basicauth_secret:
    file: config/secrets/traefik_basicauth_secret.txt
  ionos_api_key_secret:
    file: config/secrets/ionos_api_key_secret.txt
