---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.homepage${SERVICE_NAME_POST:-}.entrypoints=https
    - traefik.http.routers.homepage${SERVICE_NAME_POST:-}.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.homepage${SERVICE_NAME_POST:-}.tls=true
    - traefik.http.routers.homepage${SERVICE_NAME_POST:-}.service=homepage${SERVICE_NAME_POST:-}
    - traefik.http.services.homepage${SERVICE_NAME_POST:-}.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.homepage${SERVICE_NAME_POST:-}.loadbalancer.server.port=${PORT:-3000}
    - traefik.http.routers.homepage${SERVICE_NAME_POST:-}.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: any
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-0.2}
      memory: ${RESOURCES_LIMITS_MEMORY:-250m}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  cap_add:
    - CHOWN
    - SETGID
    - SETUID
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  networks:
    proxy: {}
  restart: always
  healthcheck:
    disable: true

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  homepage:
    # https://github.com/gethomepage/homepage/pkgs/container/homepage
    image: ghcr.io/gethomepage/homepage:${VERSION:-v0.10.9}
    <<: *basic
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      PORT: ${PORT:-3000}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - config:/app/config
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider --no-check-certificate http://localhost:$${PORT}/api/healthcheck || exit 1",
        ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10

################################################################################
################################################################################
################################################################################
networks:
  proxy:
    external: true

volumes:
  config:
    name: homepage${SERVICE_NAME_POST:-}
    # driver: local
    # driver_opts:
    #   type: nfs
    #   o: nfsvers=4.2,addr=${NFS_HOST?nfs host is not defined},rsize=2097152,wsize=2097152,tcp,nconnect=${NFS_NCON:-8}
    #   device: ":${NAS_PATH?nfs path is not defined}${SERVICE_NAME_POST:-}"
