version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  observium:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-2022}
        VERSION: ${VERSION:-latest}
    image: observium:${VERSION:-latest}
    env_file: .env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          # - "node.id==${NODE_ID}"
          - "node.role==${NODE_ROLE:-manager}"
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=${LB_SWARM:-true}
        - traefik.docker.network=proxy
        - traefik.http.routers.observium.entrypoints=https
        - traefik.http.routers.observium.rule=Host(`${DOMAIN?domain variable not set}`)
        - traefik.http.routers.observium.tls=true
        - traefik.http.routers.observium.service=observium
        - traefik.http.services.observium.loadbalancer.server.scheme=${PROTOCOL:-http}
        - traefik.http.services.observium.loadbalancer.server.port=${PORT:-80}
        - traefik.http.routers.observium.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    # ports:
    #   - target: 80
    #     published: ${PORT:-80}
    #     protocol: tcp
    #     mode: host
    environment:
      TZ: ${TZ:-Europe/Berlin}
      OBSERVIUM_ADMIN_USER: ${OBSERVIUM_ADMIN_USER:-admin}
      OBSERVIUM_ADMIN_PASS: ${OBSERVIUM_ADMIN_PASS}
      OBSERVIUM_BASE_URL: https://${DOMAIN?domain variable not set}

      OBSERVIUM_DB_HOST: ${OBSERVIUM_DB_HOST:-db}
      OBSERVIUM_DB_NAME: ${OBSERVIUM_DB_NAME:-observium}
      OBSERVIUM_DB_USER: ${OBSERVIUM_DB_USER:-observium }
      OBSERVIUM_DB_PASS: ${OBSERVIUM_DB_PASS}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - logs:/opt/observium/logs
      - rrd:/opt/observium/rrd
    networks:
      default: {}
      proxy: {}
    restart: always

  ##############################################################################
  ##############################################################################
  ##############################################################################
  db:
    image: mariadb:latest
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          # - "node.id==${NODE_ID}"
          - "node.role==${NODE_ROLE:-manager}"
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
    environment:
      TZ: ${TZ:-Europe/Berlin}
      # MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD:-yes}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER:-root}
      # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${OBSERVIUM_DB_USER:-observium}
      # MYSQL_PASSWORD: ${OBSERVIUM_DB_PASS}
      MYSQL_DATABASE: ${OBSERVIUM_DB_NAME:-observium}
    volumes:
      - db:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      default: {}
      proxy: {}
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
  proxy:
    external: true

volumes:
  logs: {}
  rrd: {}
  db: {}
