---
x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      memory: 1g

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  # cap_drop: [ "ALL" ]
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    default: {}
  tmpfs:
    - /tmp
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  app:
    # https://hub.docker.com/r/oznu/cloudflare-ddns
    image: oznu/cloudflare-ddns:${VERSION:-latest}
    <<: *basic
    deploy:
      <<: *basic-deploy
    secrets:
      - api_key_secret
    environment:
      API_KEY_FILE: /run/secrets/api_key_secret
      ZONE: ${ZONE}
      PROXIED: ${PROXIED:-true}
      RRTYPE: ${RRTYPE:-A}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      # SUBDOMAIN: ${SUBDOMAIN:-office}
      DELETE_ON_STOP: ${DELETE_ON_STOP:-true}
      DNS_SERVER: ${DNS_SERVER:-1.1.1.1}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-overlay}
    attachable: true

secrets:
  api_key_secret:
    file: config/secrets/api_key_secret.txt
