---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.swarm.lbswarm=${LB_SWARM:-true}
    - traefik.swarm.network=proxy
    - traefik.http.routers.uptime-kuma.entrypoints=https
    - traefik.http.routers.uptime-kuma.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.uptime-kuma.tls=true
    - traefik.http.routers.uptime-kuma.service=uptime-kuma
    - traefik.http.services.uptime-kuma.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.uptime-kuma.loadbalancer.server.port=${PORT:-3001}
    - traefik.http.routers.uptime-kuma.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      # cpus: "1.5"
      memory: 500M
    reservations:
      cpus: "0.001"
      memory: 32M

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  cap_add:
    - SETGID
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    proxy: {}
  tmpfs:
    - /tmp
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  uptime-kuma:
    # https://hub.docker.com/r/louislam/uptime-kuma
    image: louislam/uptime-kuma:${VERSION:-1.21.1-alpine}
    <<: *basic
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    # ports:
    #   - target: ${PORT:-3001}
    #     published: ${PORT_PUBLISH:-3001}
    #     protocol: tcp
    #     mode: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/app/data
    healthcheck:
      # disable: true
      test: ["CMD-SHELL", "node extra/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5

################################################################################
################################################################################
################################################################################
networks:
  proxy:
    external: true

volumes:
  data: {}
