---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.spiderfoot.entrypoints=https
    - traefik.http.routers.spiderfoot.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.spiderfoot.tls=true
    - traefik.http.routers.spiderfoot.service=spiderfoot
    - traefik.http.services.spiderfoot.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.spiderfoot.loadbalancer.server.port=${PORT:-5001}
    - traefik.http.routers.spiderfoot.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  cap_add:
    - NET_ADMIN
    - NET_RAW
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    # default: {}
    proxy: {}
  tmpfs:
    - /tmp
  sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.src_valid_mark=1
    - net.ipv4.conf.all.rp_filter=0
    - net.ipv4.conf.default.rp_filter=0
    - net.ipv4.conf.eth0.rp_filter=0
    - net.ipv4.conf.lo.rp_filter=0
  healthcheck:
    test: ["CMD", "curl", "-f", "${PROTOCOL:-http}://localhost:${PORT:-5001}"]
    interval: 30s
    timeout: 10s
    retries: 5
  restart: always # always | on-failure

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  spiderfoot:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: spiderfoot:${VERSION:-latest}
    <<: *basic
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    # ports:
    #   - target: 5001
    #     published: ${PORT:-5001}
    #     protocol: tcp
    #     mode: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/var/lib/spiderfoot
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  # default:
  #   driver: ${NETWORK_MODE:-overlay}
  #   attachable: true
  proxy:
    external: true

volumes:
  data: {}
