---
x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      # cpus: "1.5"
      memory: 500M
    reservations:
      cpus: "0.001"
      memory: 32M

x-basic: &basic
  privileged: true
  stdin_open: true # docker run -i
  tty: true # docker run -t
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    default: {}
  tmpfs:
    - /tmp
    - /run
  restart: on-failure

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  ubuntu:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-2023}
        VERSION: ${VERSION_UBUNTU:-23.04}
        VERSION_UBUNTU: ${VERSION_UBUNTU:-23.04}
        PYTHON_ARGS: ${PYTHON_ARGS:-}
    image: mvladislav/docker-ubuntu-systemd-sudo-ansible:${VERSION_UBUNTU:-23.04}
    <<: *basic
    deploy:
      <<: *basic-deploy
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
    driver_opts:
      encrypted: "true"
