---
x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: any
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-1}
      memory: ${RESOURCES_LIMITS_MEMORY:-1g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  privileged: true
  stdin_open: true # docker run -i
  tty: true # docker run -t
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  networks:
    default: {}
  tmpfs:
    - /tmp
    - /run
  healthcheck:
    disable: true
  restart: always

################################################################################
################################################################################
################################################################################
services:
  ubuntu:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE}
        VERSION_UBUNTU: ${VERSION_UBUNTU}
        PYTHON_ARGS: ${PYTHON_ARGS}
    image: mvladislav/docker-ubuntu-systemd-sudo-ansible:${VERSION_UBUNTU}
    <<: *basic
    deploy:
      <<: *basic-deploy
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
    driver_opts:
      encrypted: "true"
