---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.excalidraw.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.excalidraw.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.excalidraw.tls=true
    - traefik.http.routers.excalidraw.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.excalidraw.service=excalidraw
    - traefik.http.services.excalidraw.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.excalidraw.loadbalancer.server.port=${PORT:-80}

x-room-deploy-labels: &room-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.excalidraw-room.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.excalidraw-room.rule=Host(`${DOMAIN_ROOM?domain variable not set}`)
    - traefik.http.routers.excalidraw-room.tls=true
    - traefik.http.routers.excalidraw-room.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.excalidraw-room.service=excalidraw-room
    - traefik.http.services.excalidraw-room.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.excalidraw-room.loadbalancer.server.port=${PORT:-80}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: start-first
  restart_policy:
    condition: any
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-1}
      memory: ${RESOURCES_LIMITS_MEMORY:-500M}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  cap_add:
    - CHOWN
    - SETGID
    - SETUID
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  networks:
    proxy: {}
  healthcheck:
    disable: true
  restart: always

################################################################################
################################################################################
################################################################################

x-basic-env: &basic-env
  NODE_ENV: ${NODE_ENV:-production}
  # VITE_APP_BACKEND_V2_GET_URL: https://${DOMAIN_STORAGE?domain variable not set}/api/v2/
  # VITE_APP_BACKEND_V2_POST_URL: https://${DOMAIN_STORAGE?domain variable not set}/api/v2/post/
  VITE_APP_FIREBASE_CONFIG: "{}"
  VITE_APP_WS_SERVER_URL: https://${DOMAIN_ROOM?domain variable not set}
  VITE_APP_PORTAL_URL: https://${DOMAIN_ROOM?domain variable not set}

  VITE_APP_ENABLE_TRACKING: ${VITE_APP_ENABLE_TRACKING:-false}
  VITE_APP_DEBUG_ENABLE_TEXT_CONTAINER_BOUNDING_BOX: ${VITE_APP_DEBUG_ENABLE_TEXT_CONTAINER_BOUNDING_BOX:-false}
  VITE_APP_COLLAPSE_OVERLAY: ${VITE_APP_COLLAPSE_OVERLAY:-false}
  VITE_APP_ENABLE_ESLINT: ${VITE_APP_ENABLE_ESLINT:-false}

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  excalidraw:
    build:
      context: .
      dockerfile: ./Dockerfile
      # context: https://github.com/excalidraw/excalidraw.git#${VERSION_EXCALIDRAW:-v0.17.6}
      # dockerfile: ./Dockerfile
      args:
        <<: *basic-env
        VERSION_EXCALIDRAW: v0.17.6
    image: excalidraw:${VERSION_EXCALIDRAW:-v0.17.6}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    environment:
      <<: *basic-env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # - ./:/opt/node_app/app:delegated
      # - ./package.json:/opt/node_app/package.json
      # - ./yarn.lock:/opt/node_app/yarn.lock
      - notused:/opt/node_app/app/node_modules
    # healthcheck:
    #   test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost || exit 1"]
    #   start_period: 2s
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5

  ##############################################################################
  ##############################################################################
  ##############################################################################
  excalidraw-room:
    build:
      context: https://github.com/excalidraw/excalidraw-room.git#${VERSION_EXCALIDRAW_ROOM_GIT:-master}
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
    image: excalidraw-room:${VERSION_EXCALIDRAW_ROOM:-v0.17.6}
    <<: [*basic, *room-deploy-labels]
    deploy:
      <<: [*basic-deploy, *room-deploy-labels]
    environment:
      PORT: ${PORT:-80}
      CORS_ORIGIN: ${DOMAIN_ROOM?domain variable not set}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

################################################################################
################################################################################
################################################################################
networks:
  proxy:
    external: true

volumes:
  notused: {}
