version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-2022}
        VERSION: ${VERSION:-latest}
        PYTHON_VERSION: 3.6.12-alpine3.12
        GROUP: 1000
        USER: 1000
    image: sophos:${VERSION:-latest}
    # stdin_open: true # docker run -i
    # tty: true # docker run -t
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          # - "node.id==${NODE_ID}"
          - "node.role==${NODE_ROLE:-manager}"
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
    environment:
      SOPHOS_SIEM_HOME: /app/sophos
    # configs:
    #   - source: crontab_config
    #     target: /etc/crontab
    #     mode: 0440
    #     uid: "1000"
    #     gid: "1000"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - logs:/var/log/sophos:rw
      # - ./config/crontab:/etc/crontab:ro
    networks:
      default: {}
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true

volumes:
  logs: {}
#
# configs:
#   crontab_config:
#     file: $PWD/config/crontab
