---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.swarm.lbswarm=${LB_SWARM:-true}
    - traefik.swarm.network=proxy
    - traefik.http.routers.velociraptor${SERVICE_NAME_POST:-}.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.velociraptor${SERVICE_NAME_POST:-}.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.velociraptor${SERVICE_NAME_POST:-}.tls=true
    - traefik.http.routers.velociraptor${SERVICE_NAME_POST:-}.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.velociraptor${SERVICE_NAME_POST:-}.service=velociraptor${SERVICE_NAME_POST:-}
    - traefik.http.services.velociraptor${SERVICE_NAME_POST:-}.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.velociraptor${SERVICE_NAME_POST:-}.loadbalancer.server.port=${PORT:-8889}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: any
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-1}
      memory: ${RESOURCES_LIMITS_MEMORY:-1g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  # cap_add:
  #   - CHOWN # (chmod)
  #   - DAC_OVERRIDE
  #   - DAC_READ_SEARCH
  #   - SETGID # (setgroups)
  #   - SETUID # (setuid)
  #   - FOWNER # (chmod, chown, or chgrp)
  #   - FSETID
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  networks:
    proxy: {}
  healthcheck:
    disable: true
  restart: always

################################################################################
################################################################################
################################################################################
services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  velociraptor:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VERSION: latest
        VERSION_UBUNTU: ${VERSION_UBUNTU:-24.04}
    image: velociraptor:${VERSION:-latest}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    # ports:
    #   - target: ${PORT:-8000}
    #     published: ${PORT_PUBLISH:-8000}
    #     protocol: tcp
    #     mode: host
    #   - target: ${PORT_2:-8889}
    #     published: ${PORT_2_PUBLISH:-8889}
    #     protocol: tcp
    #     mode: host
    secrets:
      - velox_password_secret
    environment:
      VELOX_USER: ${VELOX_USER:-groot}
      VELOX_PASSWORD_FILE: /run/secrets/velox_password_secret
      VELOX_ROLE: ${VELOX_ROLE:-administrator}
      VELOX_SERVER_URL: https://${DOMAIN}/
      VELOX_FRONTEND_HOSTNAME: ${DOMAIN}
      USE_PLAIN_HTTP: ${USE_PLAIN_HTTP:-true}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/velociraptor

################################################################################
################################################################################
################################################################################
networks:
  proxy:
    external: true

volumes:
  data:
    name: data

secrets:
  velox_password_secret:
    file: config/secrets/velox_password_secret.txt
