#!/usr/bin/env bash

code-server --install-extension aaron-bond.better-comments
code-server --install-extension adpyke.codesnap
code-server --install-extension adpyke.vscode-sql-formatter
code-server --install-extension analytic-signal.preview-pdf
code-server --install-extension benjaminkott.typo3-typoscript
code-server --install-extension bibhasdn.unique-lines
code-server --install-extension bierner.markdown-emoji
code-server --install-extension bierner.markdown-preview-github-styles
code-server --install-extension charliermarsh.ruff
code-server --install-extension ChrisChinchilla.vscode-pandoc
code-server --install-extension DavidAnson.vscode-markdownlint
code-server --install-extension dbaeumer.vscode-eslint
code-server --install-extension DotJoshJohnson.xml
code-server --install-extension eamodio.gitlens
code-server --install-extension esbenp.prettier-vscode
code-server --install-extension febley.typo3-fluid-snippets
code-server --install-extension foxundermoon.shell-format
code-server --install-extension golang.go
code-server --install-extension James-Yu.latex-workshop
code-server --install-extension mechatroner.rainbow-csv
code-server --install-extension mhutchie.git-graph
code-server --install-extension mikestead.dotenv
code-server --install-extension ms-python.black-formatter
code-server --install-extension ms-python.flake8
code-server --install-extension ms-python.isort
code-server --install-extension ms-python.python
code-server --install-extension ms-python.vscode-pylance
code-server --install-extension ms-vscode.hexeditor
code-server --install-extension mushan.vscode-paste-image
code-server --install-extension PKief.material-icon-theme
code-server --install-extension ralffreit.typo3snippets
code-server --install-extension rangav.vscode-thunder-client
code-server --install-extension redhat.ansible
code-server --install-extension redhat.vscode-xml
code-server --install-extension redhat.vscode-yaml
code-server --install-extension rome.rome
code-server --install-extension scala-lang.scala
code-server --install-extension secsamdev.grok
code-server --install-extension silofy.hackthebox
code-server --install-extension SimonSiefke.svg-preview
code-server --install-extension streetsidesoftware.code-spell-checker
code-server --install-extension streetsidesoftware.code-spell-checker-german
code-server --install-extension timonwong.shellcheck
code-server --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code-server --install-extension VisualStudioExptTeam.vscodeintellicode
code-server --install-extension wayou.vscode-todo-highlight
code-server --install-extension wholroyd.jinja
code-server --install-extension yzane.markdown-pdf
code-server --install-extension yzhang.markdown-all-in-one
