version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  gophish:
    image: gophish/gophish:${VERSION:-latest}
    env_file: .env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          # - "node.id==${NODE_ID}"
          - "node.role==${NODE_ROLE:-manager}"
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=${LB_SWARM:-true}
        - traefik.docker.network=proxy
        - traefik.http.routers.gophish.entrypoints=https
        - traefik.http.routers.gophish.rule=Host(`${DOMAIN?domain variable not set}`)
        - traefik.http.routers.gophish.tls=true
        - traefik.http.routers.gophish.service=gophish
        - traefik.http.services.gophish.loadbalancer.server.scheme=${PROTOCOL:-http}
        - traefik.http.services.gophish.loadbalancer.server.port=${PORT:-3333}
        - traefik.http.routers.gophish.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    # ports:
    #   - target: 3333
    #     published: ${PORT:-3333}
    #     protocol: tcp
    #     mode: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      proxy: {}
    healthcheck:
      test: ["CMD", "curl", "-f", "${PROTOCOL:-http}://localhost:${PORT:-3333}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  proxy:
    external: true
