---
# global config
global:
  scrape_interval: 15s # scrape targets every 15 seconds
  evaluation_interval: 15s # scrape targets every 15 seconds
  # scrape_timeout is set to the global default (10s).

rule_files:
  - "alert.rules"

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "traefik"
    # scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - traefik:8080
