name: Greetings

on:
  - pull_request_target
  - issues

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          issue-message: >
            Thanks for opening your first issue here!
            Be sure to follow the bug or feature issue templates!
          pr-message: >
            Thanks for opening this pull request!
            Be sure to follow the pull request template!
          repo-token: ${{ secrets.GITHUB_TOKEN }}
