---
version: "3.8"

################################################################################
################################################################################
################################################################################

x-basic-deploy:
  &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      # cpus: "1.5"
      memory: 500M
    reservations:
      cpus: "0.001"
      memory: 32M

x-basic:
  &basic
  env_file: .env
  # cap_add:
  #   - NET_ADMIN
  #   - NET_RAW
  cap_drop: [ "ALL" ]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    default: {}
  # network_mode: host
  tmpfs:
    - /tmp
  sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.src_valid_mark=1
    - net.ipv4.conf.all.rp_filter=0
    - net.ipv4.conf.default.rp_filter=0
    - net.ipv4.conf.eth0.rp_filter=0
    - net.ipv4.conf.lo.rp_filter=0
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.all.disable_ipv6=0
  restart: on-failure

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  cloudflared:
    # https://hub.docker.com/r/cloudflare/cloudflared
    image: cloudflare/cloudflared:${VERSION:-2022.12.1}
    <<: *basic
    deploy:
      <<: *basic-deploy
    environment:
      TUNNEL_TOKEN: ${TOKEN}
      NO_AUTOUPDATE: ${NO_AUTOUPDATE:-true}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: tunnel run

################################################################################
################################################################################
################################################################################
networks:
  default:
    name: cloudflare-tunnel
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
    driver_opts:
      encrypted: "true"
