version: "3.8"

services:
  ######################################################################################
  ######################################################################################
  ######################################################################################
  influxdb:
    image: influxdb:${VERSION:-latest}
    env_file: .env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==${NODE_ROLE:-manager}"
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=${LB_SWARM:-true}
        - traefik.docker.network=proxy
        - traefik.http.routers.influxdb.entrypoints=https
        - traefik.http.routers.influxdb.rule=Host(`${DOMAIN?domain variable not set}`)
        - traefik.http.routers.influxdb.tls=true
        - traefik.http.routers.influxdb.service=influxdb
        - traefik.http.services.influxdb.loadbalancer.server.scheme=${PROTOCOL:-http}
        - traefik.http.services.influxdb.loadbalancer.server.port=${PORT:-8086}
        - traefik.http.routers.influxdb.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    # ports:
    #   - target: 8086
    #     published: ${PORT:-8086}
    #     protocol: tcp
    #     mode: host
    # configs:
    #   - source: crt_config
    #     target: /etc/ssl/influxdb-selfsigned.crt
    #   - source: key_config
    #     target: /etc/ssl/influxdb-selfsigned.key
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - influxdb2-storage:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: ${DOCKER_INFLUXDB_INIT_MODE:-setup}
      DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_INIT_USERNAME:-root}
      # DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD:-}
      DOCKER_INFLUXDB_INIT_ORG: ${DOCKER_INFLUXDB_INIT_ORG:-my_orga}
      DOCKER_INFLUXDB_INIT_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET:-db0}
      # DOCKER_INFLUXDB_INIT_RETENTION: ${DOCKER_INFLUXDB_INIT_RETENTION:-1w}
      # DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN:-my-super-secret-auth-token}
      # INFLUXD_TLS_CERT: /etc/ssl/influxdb-selfsigned.crt
      # INFLUXD_TLS_KEY: /etc/ssl/influxdb-selfsigned.key
    networks:
      influxdb2: {}
      proxy: {}
    restart: always

######################################################################################
######################################################################################
######################################################################################
networks:
  influxdb2:
    name: influxdb2
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
  proxy:
    external: true

volumes:
  influxdb2-storage: {}
  influxdb2-config: {}
#
# configs:
#   crt_config:
#     file: $PWD/config/ssl/influxdb-selfsigned.crt
#   key_config:
#     file: $PWD/config/ssl/influxdb-selfsigned.key
