version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  traefik:
    # https://hub.docker.com/_/traefik
    image: traefik:${VERSION:-latest}
    env_file: .env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==${NODE_ROLE:-manager}"
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=${LB_SWARM:-true}
        - traefik.docker.network=proxy

        - traefik.http.routers.traefik.entrypoints=https
        - traefik.http.routers.traefik.rule=Host(`${DOMAIN?domain variable not set}`)
        - traefik.http.routers.traefik.tls=true
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.services.traefik.loadbalancer.server.scheme=${PROTOCOL:-http}
        - traefik.http.services.traefik.loadbalancer.server.port=${PORT:-8080}
        - traefik.http.routers.traefik.middlewares=${MIDDLEWARE_SECURED:-admin-secured@file}
        # admin-auth middleware with HTTP Basic auth
        # Using the environment variables ADMIN_USERNAME and HASHED_PASSWORD
        - traefik.http.routers.traefik.middlewares=admin-auth
        - traefik.http.middlewares.admin-auth.basicauth.users=${ADMIN_USERNAME?username variable not set}:${HASHED_PASSWORD?password hash variable not set}
    ports:
      - target: 80 # http
        published: 80
        protocol: tcp
        mode: host
      - target: 443 # https
        published: 443
        protocol: tcp
        mode: host
      # -------------------------------------
      # - target: 139 # smb
      #   published: 139
      #   protocol: tcp
      #   mode: host
      # - target: 445 # smb
      #   published: 445
      #   protocol: tcp
      #   mode: host
      # - target: 3128 # spice
      #   published: 3128
      #   protocol: tcp
      #   mode: host
      # -------------------------------------
      # - target: 3306 # mysql
      #   published: 3306
      #   protocol: tcp
      #   mode: host
      # - target: 5432 # postgress
      #   published: 5432
      #   protocol: tcp
      #   mode: host
      # - target: 8086 # influxdb
      #   published: 8086
      #   protocol: tcp
      #   mode: host
      # - target: 9090 # prometheus
      #   published: 9090
      #   protocol: tcp
      #   mode: host
      # -------------------------------------
      # - target: 9200 # elastic - send metrics direct to elastic
      #   published: 9200
      #   protocol: tcp
      #   mode: host
      # - target: 8220 # elastic-agent - access elastic over installed agent
      #   published: 8220
      #   protocol: tcp
      #   mode: host
      # - target: 5044 # elastic-beats - logtash used for example sysmon
      #   published: 5044
      #   protocol: tcp
      #   mode: host
      # -------------------------------------
      # - target: 5140 # syslog-opnsense - logstash syslogs collector
      #   published: 5140
      #   protocol: tcp
      #   mode: host
      # - target: 5145 # syslog-unifi - logstash syslogs collector
      #   published: 5145
      #   protocol: udp
      #   mode: host
      # - target: 2055 # netflow - filebeat netflow collector
      #   published: 2055
      #   protocol: udp
      #   mode: host
      # -------------------------------------
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik.yml
        mode: 440
      - source: traefik_config_http
        target: /etc/traefik/config.yml
        mode: 440
      - source: traefik_ca_config
        target: /etc/traefik/certs/ca.pem
        mode: 440
      - source: traefik_crt_config
        target: /etc/traefik/certs/cert.pem
        mode: 440
      - source: traefik_key_config
        target: /etc/traefik/certs/cert-key.pem
        mode: 440
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_logs:/var/log/traefik
    networks:
      proxy: {}
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  proxy:
    name: proxy
    driver: ${NETWORK_MODE:-bridge}
    attachable: true

volumes:
  config: {}
  traefik_logs:
    name: traefik_logs

configs:
  traefik_config:
    file: $PWD/config/traefik.yml
  traefik_config_http:
    file: $PWD/config/config.yml
  traefik_ca_config:
    file: $PWD/config/ssl/ca.pem
  traefik_crt_config:
    file: $PWD/config/ssl/cert.pem
  traefik_key_config:
    file: $PWD/config/ssl/cert-key.pem
