version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  uptime_kuma:
    image: louislam/uptime-kuma:${VERSION:-latest}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          # - "node.id==${NODE_ID}"
          - "node.role==${NODE_ROLE:-manager}"
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=true
        - traefik.docker.network=proxy
        - traefik.http.routers.kuma.entrypoints=https
        - traefik.http.routers.kuma.rule=Host(`${DOMAIN?domain variable not set}`)
        - traefik.http.routers.kuma.tls=true
        - traefik.http.routers.kuma.service=kuma
        - traefik.http.services.kuma.loadbalancer.server.scheme=${PROTOCOL:-http}
        - traefik.http.services.kuma.loadbalancer.server.port=${PORT:-3001}
        - traefik.http.routers.kuma.middlewares=default-secured@file
    # ports:
    #   - target: 3001
    #     published: ${PORT:-3001}
    #     protocol: tcp
    #     mode: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/app/data
    networks:
      # default: {}
      proxy: {}
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  # default:
  #   driver: ${NETWORK_MODE:-bridge}
  #   attachable: true
  proxy:
    external: true

volumes:
  data: {}
