version: "3.8"

services:
  ######################################################################################
  ######################################################################################
  ######################################################################################
  grafana:
    image: grafana/grafana:${VERSION:-latest}
    env_file: .env
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==${NODE_ROLE:-manager}"
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=true
        - traefik.docker.network=proxy
        - traefik.http.routers.grafana.entrypoints=https
        - traefik.http.routers.grafana.rule=Host(`${DOMAIN?domain variable not set}`)
        - traefik.http.routers.grafana.tls=true
        - traefik.http.routers.grafana.service=grafana
        - traefik.http.services.grafana.loadbalancer.server.scheme=${PROTOCOL:-http}
        - traefik.http.services.grafana.loadbalancer.server.port=${PORT:-3000}
        - traefik.http.routers.grafana.middlewares=protected-secured@file
    # ports:
    #   - target: 3000
    #     published: ${PORT:-3443}
    #     mode: host
    # configs:
    #   - source: crt_config
    #     target: /etc/ssl/grafana-selfsigned.crt
    #   - source: key_config
    #     target: /etc/ssl/grafana-selfsigned.key
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - grafana-storage:/var/lib/grafana
      # - provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-root}
      # GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: ${GF_USERS_ALLOW_SIGN_UP:-false}
      GF_SERVER_DOMAIN: ${GF_SERVER_DOMAIN:-grafana.home.local}
      GF_SMTP_ENABLED: ${GF_SMTP_ENABLED:-false}
      GF_SMTP_HOST: ${GF_SMTP_HOST:-}
      GF_SMTP_USER: ${GF_SMTP_USER:-}
      # GF_SMTP_PASSWORD: ${GF_SMTP_PASSWORD:-}
      GF_SMTP_FROM_ADDRESS: ${GF_SMTP_FROM_ADDRESS:-}
      GF_INSTALL_PLUGINS: magnesium-wordcloud-panel,flant-statusmap-panel,grafana-piechart-panel,grafana-worldmap-panel,mxswat-separator-panel
      # "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource"
      # GF_SERVER_PROTOCOL: https
      # GF_SERVER_CERT_FILE: /etc/ssl/grafana-selfsigned.crt
      # GF_SERVER_CERT_KEY: /etc/ssl/grafana-selfsigned.key
    networks:
      proxy: {}
      elasticsearch: {}
      influxdb2: {}
    restart: always

######################################################################################
######################################################################################
######################################################################################
networks:
  proxy:
    external: true
  elasticsearch:
    external: true
    name: elasticsearch
  influxdb2:
    external: true
    name: influxdb2

volumes:
  grafana-storage: {}

# configs:
#   crt_config:
#     file: $PWD/config/ssl/grafana-selfsigned.crt
#   key_config:
#     file: $PWD/config/ssl/grafana-selfsigned.key
