---
version: "3.8"

################################################################################
################################################################################
################################################################################

x-basic-deploy-labels:
  &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.grafana.entrypoints=https
    - traefik.http.routers.grafana.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.grafana.tls=true
    - traefik.http.routers.grafana.service=grafana
    - traefik.http.services.grafana.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.grafana.loadbalancer.server.port=${PORT:-3000}
    - traefik.http.routers.grafana.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}

x-basic-deploy:
  &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      # cpus: "1.5"
      memory: 2g
    reservations:
      cpus: "0.001"
      memory: 32M

x-basic:
  &basic
  env_file: .env
  # cap_add:
  #   # https://dockerlabs.collabnix.com/advanced/security/capabilities/
  #   - CHOWN
  #   - DAC_OVERRIDE
  #   - DAC_READ_SEARCH
  #   - SETGID
  #   - SETUID
  #   - NET_ADMIN
  #   - NET_RAW
  #   - NET_BIND_SERVICE
  #   - NET_BROADCAST
  #   - SYS_MODULE
  #   - SYS_NICE
  #   - AUDIT_CONTROL
  #   - AUDIT_READ
  cap_drop: [ "ALL" ]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    proxy: {}
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  grafana:
    # https://hub.docker.com/r/grafana/grafana
    image: grafana/grafana:${VERSION:-9.4.3}
    user: "$UID:$GID"
    <<: *basic
    deploy:
      <<: [ *basic-deploy, *basic-deploy-labels ]
    # ports:
    #   - target: ${PORT:-3000}
    #     published: ${PORT_PUBLISH:-3000}
    #     protocol: tcp
    #     mode: host
    secrets:
      - admin_password_file_secret
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-root}
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/admin_password_file_secret
      GF_USERS_ALLOW_SIGN_UP: ${GF_USERS_ALLOW_SIGN_UP:-false}
      GF_SERVER_DOMAIN: ${DOMAIN?domain variable not set}
      GF_SMTP_ENABLED: ${GF_SMTP_ENABLED:-false}
      GF_SMTP_HOST: ${GF_SMTP_HOST:-}
      GF_SMTP_USER: ${GF_SMTP_USER:-}
      # GF_SMTP_PASSWORD: ${GF_SMTP_PASSWORD:-}
      GF_SMTP_FROM_ADDRESS: ${GF_SMTP_FROM_ADDRESS:-}
      GF_INSTALL_PLUGINS: magnesium-wordcloud-panel,flant-statusmap-panel,grafana-piechart-panel,grafana-worldmap-panel,mxswat-separator-panel
      # "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - grafana-storage:/var/lib/grafana
      - grafana-plugins:/usr/share/grafana/plugins-bundled
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "--no-check-certificate",
          "${PROTOCOL:-http}://127.0.0.1:${PORT:-3000}/api/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 5

################################################################################
################################################################################
################################################################################
networks:
  proxy:
    external: true

volumes:
  grafana-storage: {}
  grafana-plugins: {}

secrets:
  admin_password_file_secret:
    file: config/secrets/admin_password_file_secret.txt
