---
version: "3.8"

################################################################################
################################################################################
################################################################################

x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.fireflyiii.entrypoints=https
    - traefik.http.routers.fireflyiii.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.fireflyiii.tls=true
    - traefik.http.routers.fireflyiii.service=fireflyiii
    - traefik.http.services.fireflyiii.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.fireflyiii.loadbalancer.server.port=${PORT:-8080}
    - traefik.http.routers.fireflyiii.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-1}
      memory: ${RESOURCES_LIMITS_MEMORY:-1g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: .env
  # cap_add:
  #   # https://dockerlabs.collabnix.com/advanced/security/capabilities/
  #   - CHOWN
  #   - DAC_OVERRIDE
  #   - DAC_READ_SEARCH
  #   - SETGID
  #   - SETUID
  #   - NET_ADMIN
  #   - NET_RAW
  #   - NET_BIND_SERVICE
  #   - NET_BROADCAST
  #   - SYS_MODULE
  #   - SYS_NICE
  #   - AUDIT_CONTROL
  #   - AUDIT_READ
  cap_add: ["ALL"] # TODO: remove only test
  # cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    default: {}
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  fireflyiii:
    # https://hub.docker.com/r/fireflyiii/core
    image: fireflyiii/core:${VERSION_FIREFLY:-version-6.0.26}
    <<: *basic
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    secrets:
      - fireflyiii_password
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-false}
      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE:-de_DE}
      DEFAULT_LOCALE: ${DEFAULT_LOCALE:-equal}
      TZ: ${TZ:-Europe/Berlin}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-**}
      LOG_CHANNEL: ${LOG_CHANNEL:-stack}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL:-notice}
      AUDIT_LOG_LEVEL: ${AUDIT_LOG_LEVEL:-emergency}
      AUDIT_LOG_CHANNEL: ${AUDIT_LOG_CHANNEL:-}

      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST:-fireflyiii_db}
      DB_PORT: ${DB_PORT:-3306}
      DB_USERNAME: ${DB_USERNAME:-firefly}
      DB_DATABASE: ${DB_DATABASE:-firefly}
      DB_PASSWORD_FILE: /run/secrets/fireflyiii_password

      CACHE_DRIVER: ${CACHE_DRIVER:-file}
      SESSION_DRIVER: ${SESSION_DRIVER:-file}

      COOKIE_PATH: ${COOKIE_PATH:-"/"}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN:-}
      COOKIE_SECURE: ${COOKIE_SECURE:-false}
      COOKIE_SAMESITE: ${COOKIE_SAMESITE:-lax}

      SEND_ERROR_MESSAGE: ${SEND_ERROR_MESSAGE:-true}
      SEND_REPORT_JOURNALS: ${SEND_REPORT_JOURNALS:-true}
      ENABLE_EXTERNAL_MAP: ${ENABLE_EXTERNAL_MAP:-false}
      ENABLE_EXTERNAL_RATES: ${ENABLE_EXTERNAL_RATES:-false}
      MAP_DEFAULT_LAT: ${MAP_DEFAULT_LAT:-51.983333}
      MAP_DEFAULT_LONG: ${MAP_DEFAULT_LONG:-5.916667}
      MAP_DEFAULT_ZOOM: ${MAP_DEFAULT_ZOOM:-6}

      AUTHENTICATION_GUARD: ${AUTHENTICATION_GUARD:-web}
      AUTHENTICATION_GUARD_HEADER: ${AUTHENTICATION_GUARD_HEADER:-REMOTE_USER}
      AUTHENTICATION_GUARD_EMAIL: ${AUTHENTICATION_GUARD_EMAIL:-}
      PASSPORT_PRIVATE_KEY: ${PASSPORT_PRIVATE_KEY:-}
      PASSPORT_PUBLIC_KEY: ${PASSPORT_PUBLIC_KEY:-}
      DISABLE_FRAME_HEADER: ${DISABLE_FRAME_HEADER:-false}
      DISABLE_CSP_HEADER: ${DISABLE_CSP_HEADER:-false}
      ALLOW_WEBHOOKS: ${ALLOW_WEBHOOKS:-false}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - firefly_iii_upload:/var/www/html/storage/upload
    networks:
      default: {}
      proxy: {}
    healthcheck:
      disable: true

  ##############################################################################
  ##############################################################################
  ##############################################################################
  fireflyiii_db:
    # https://hub.docker.com/_/mariadb
    image: mariadb:${VERSION_DB:-11.1.2}
    <<: *basic
    deploy:
      <<: *basic-deploy
    cap_add:
      - SYS_NICE
      - DAC_OVERRIDE
      - CHOWN
      - SETGID
      - SETUID
    secrets:
      - mariadb_root_password
      - mariadb_user_password
    environment:
      TZ: ${TZ:-Europe/Berlin}
      MYSQL_USER: ${DB_USERNAME:-firefly}
      MYSQL_DATABASE: ${DB_DATABASE:-firefly}
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mariadb_user_password
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - firefly_iii_db:/var/lib/mysql
    command:
      - --log-bin=mysql-bin
      - --expire-logs-days=7
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh --no-defaults"]
      interval: 30s
      timeout: 10s
      retries: 5

  ##############################################################################
  ##############################################################################
  ##############################################################################
  fireflyiii_cron:
    # https://hub.docker.com/_/alpine
    image: alpine:${VERSION_ALPINE:-3.18.3}
    <<: *basic
    deploy:
      <<: *basic-deploy
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME\" | crontab - && crond -f -L /dev/stdout"
    healthcheck:
      disable: true

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
    driver_opts:
      encrypted: "true"
  proxy:
    external: true

volumes:
  firefly_iii_upload: {}
  firefly_iii_db: {}

secrets:
  fireflyiii_password:
    file: config/secrets/fireflyiii_password.txt
  mariadb_root_password:
    file: config/secrets/mariadb_root_password.txt
  mariadb_user_password:
    file: config/secrets/mariadb_user_password.txt
