---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.docker.lbswarm=${LB_SWARM:-true}
    - traefik.docker.network=proxy
    - traefik.http.routers.nexpose.entrypoints=https
    - traefik.http.routers.nexpose.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.nexpose.tls=true
    - traefik.http.routers.nexpose.service=nexpose
    - traefik.http.services.nexpose.loadbalancer.server.scheme=${PROTOCOL:-https}
    - traefik.http.services.nexpose.loadbalancer.server.port=${PORT:-3780}
    - traefik.http.routers.nexpose.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  restart_policy:
    condition: on-failure

x-basic: &basic
  env_file: .env
  # privileged: true
  cap_add:
    - NET_ADMIN
    - NET_RAW
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65535
      hard: 65535
    fsize: -1
    as: -1
  networks:
    default: {}
    proxy: {}
  tmpfs:
    - /tmp
  sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.src_valid_mark=1
    - net.ipv4.conf.all.rp_filter=0
    - net.ipv4.conf.default.rp_filter=0
    - net.ipv4.conf.eth0.rp_filter=0
    - net.ipv4.conf.lo.rp_filter=0
  restart: always # always | on-failure

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  nexpose:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-2022}
        VERSION: ${VERSION:-latest}
    image: nexpose:${VERSION:-latest}
    stdin_open: true # docker run -i
    tty: true # docker run -t
    <<: *basic
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    ports:
      - target: 3780
        published: ${PORT:-3780}
        protocol: tcp
        mode: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - conf:/opt/rapid7/nexpose/nse/conf
      - keystores:/opt/rapid7/nexpose/nse/keystores
      - logs:/opt/rapid7/nexpose/nse/logs
      - scans:/opt/rapid7/nexpose/nse/scans
      - plugins:/opt/rapid7/nexpose/plugins
      - updates:/opt/rapid7/nexpose/updates
      # - nsc:/opt/rapid7/nexpose/nsc
      ################################################################################
      ################################################################################
      ################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
  proxy:
    external: true

volumes:
  conf: {}
  keystores: {}
  logs: {}
  scans: {}
  plugins: {}
  updates: {}
  # nsc: {}
