---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.swarm.lbswarm=${LB_SWARM:-true}
    - traefik.swarm.network=proxy
    - traefik.http.routers.openvas.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.openvas.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.openvas.tls=true
    - traefik.http.routers.openvas.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.openvas.service=openvas
    - traefik.http.services.openvas.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.openvas.loadbalancer.server.port=${PORT:-80}
    - traefik.http.services.openvas.loadbalancer.sticky=true
    - traefik.http.services.openvas.loadbalancer.sticky.cookie.name=stickycookie
    - traefik.http.services.openvas.loadbalancer.sticky.cookie.secure=true
    - traefik.http.services.openvas.loadbalancer.sticky.cookie.httpOnly=true

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: on-failure
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-2}
      memory: ${RESOURCES_LIMITS_MEMORY:-3g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic-deploy-conf: &basic-deploy-conf
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: on-failure
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS_CONF:-0.5}
      memory: ${RESOURCES_LIMITS_MEMORY_CONF:-250m}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS_CONF:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY_CONF:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  cap_add: ["ALL"]
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  networks:
    default: {}
  healthcheck:
    disable: true
  tmpfs:
    - /tmp
  sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.src_valid_mark=1
    - net.ipv4.conf.all.rp_filter=0
    - net.ipv4.conf.default.rp_filter=0
    - net.ipv4.conf.lo.rp_filter=0
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.all.disable_ipv6=0

# x-basic-cap:
#   &basic-cap
#   cap_add:
#     - SETFCAP
#     - SETGID
#     - SETUID

# x-basic-cap-net:
#   &basic-cap-net
#   cap_add:
#     - NET_ADMIN # for capturing packages in promiscuous mode
#     - NET_RAW # for raw sockets e.g. used for the boreas alive detection
#     - SETFCAP
#     - SETGID
#     - SETUID

# x-basic-cap-files:
#   &basic-cap-files
#   cap_add:
#     - CHOWN
#     - FOWNER
#     - SETGID
#     - SETUID
#     - DAC_OVERRIDE

################################################################################
################################################################################
################################################################################
services:
  gsa:
    image: registry.community.greenbone.net/community/gsa:${VERSION_GSA:-stable}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    restart: on-failure
    volumes:
      - gvmd_socket_vol:/run/gvmd
    networks:
      default: {}
      proxy: {}

  gvmd:
    image: registry.community.greenbone.net/community/gvmd:${VERSION_GVMD:-stable}
    <<: *basic
    deploy:
      <<: *basic-deploy
    restart: on-failure
    volumes:
      - gvmd_data_vol:/var/lib/gvm
      - scap_data_vol:/var/lib/gvm/scap-data/
      - cert_data_vol:/var/lib/gvm/cert-data
      - data_objects_vol:/var/lib/gvm/data-objects/gvmd
      - vt_data_vol:/var/lib/openvas/plugins
      - psql_data_vol:/var/lib/postgresql
      - gvmd_socket_vol:/run/gvmd
      - ospd_openvas_socket_vol:/run/ospd
      - psql_socket_vol:/var/run/postgresql

  openvasd:
    image: registry.community.greenbone.net/community/openvas-scanner:${VERSION_NOTUS_SCANNER:-stable}
    <<: *basic
    deploy:
      <<: *basic-deploy
    restart: on-failure
    environment:
      OPENVASD_MODE: service_notus
      GNUPGHOME: /etc/openvas/gnupg
      LISTENING: 0.0.0.0:80
    volumes:
      - openvas_data_vol:/etc/openvas
      - openvas_log_data_vol:/var/log/openvas
      - gpg_data_vol:/etc/openvas/gnupg
      - notus_data_vol:/var/lib/notus

  ospd-openvas:
    image: registry.community.greenbone.net/community/ospd-openvas:${VERSION_OSPD_OPENVAS:-stable}
    <<: *basic
    deploy:
      <<: *basic-deploy
    restart: on-failure
    # cap_add:
    #   - NET_ADMIN # for capturing packages in promiscuous mode
    #   - NET_RAW # for raw sockets e.g. used for the boreas alive detection
    # security_opt:
    #   - seccomp=unconfined
    #   - apparmor=unconfined
    # configs:
    #   - source: openvas_config
    #     target: /etc/openvas/openvas.conf
    #     mode: 0644
    #     uid: "19654"
    #     gid: "19654"
    command:
      [
        "ospd-openvas",
        "-f",
        "--config",
        "/etc/gvm/ospd-openvas.conf",
        "--notus-feed-dir",
        "/var/lib/notus/advisories",
        "-m",
        "666",
      ]
    volumes:
      - gpg_data_vol:/etc/openvas/gnupg
      - vt_data_vol:/var/lib/openvas/plugins
      - notus_data_vol:/var/lib/notus
      - ospd_openvas_socket_vol:/run/ospd
      - redis_socket_vol:/run/redis/
      - openvas_data_vol:/etc/openvas/
      - openvas_log_data_vol:/var/log/openvas

  pg-gvm:
    image: registry.community.greenbone.net/community/pg-gvm:${VERSION_PG_GVM:-stable}
    <<: *basic
    deploy:
      <<: *basic-deploy
    restart: on-failure
    volumes:
      - psql_data_vol:/var/lib/postgresql
      - psql_socket_vol:/var/run/postgresql

  redis-server:
    image: registry.community.greenbone.net/community/redis-server:${VERSION_LATEST:-latest}
    <<: *basic
    deploy:
      <<: *basic-deploy
    restart: on-failure
    volumes:
      - redis_socket_vol:/run/redis/

  ##############################################################################
  ##############################################################################
  ##############################################################################

  vulnerability-tests:
    image: registry.community.greenbone.net/community/vulnerability-tests:${VERSION_LATEST:-latest}
    <<: *basic
    deploy:
      <<: *basic-deploy
    environment:
      FEED_RELEASE: ${FEED_RELEASE:-24.10}
    volumes:
      - vt_data_vol:/mnt

  ##############################################################################
  ##############################################################################
  ##############################################################################

  # shows logs of openvas
  openvas:
    image: registry.community.greenbone.net/community/openvas-scanner:${VERSION_NOTUS_SCANNER:-stable}
    <<: *basic
    deploy:
      <<: *basic-deploy-conf
    restart: on-failure
    volumes:
      - openvas_data_vol:/etc/openvas
      - openvas_log_data_vol:/var/log/openvas
    command:
      - /bin/sh
      - -c
      - |
        cat /etc/openvas/openvas.conf
        tail -f /var/log/openvas/openvas.log

  ##############################################################################
  ##############################################################################
  ##############################################################################

  notus-data:
    image: registry.community.greenbone.net/community/notus-data:${VERSION_LATEST:-latest}
    <<: *basic
    deploy:
      <<: *basic-deploy-conf
    volumes:
      - notus_data_vol:/mnt

  scap-data:
    image: registry.community.greenbone.net/community/scap-data:${VERSION_LATEST:-latest}
    <<: *basic
    deploy:
      <<: *basic-deploy-conf
    volumes:
      - scap_data_vol:/mnt

  cert-bund-data:
    image: registry.community.greenbone.net/community/cert-bund-data:${VERSION_LATEST:-latest}
    <<: *basic
    deploy:
      <<: *basic-deploy-conf
    volumes:
      - cert_data_vol:/mnt

  dfn-cert-data:
    image: registry.community.greenbone.net/community/dfn-cert-data:${VERSION_LATEST:-latest}
    <<: *basic
    deploy:
      <<: *basic-deploy-conf
    volumes:
      - cert_data_vol:/mnt

  data-objects:
    image: registry.community.greenbone.net/community/data-objects:${VERSION_LATEST:-latest}
    <<: *basic
    deploy:
      <<: *basic-deploy-conf
    environment:
      FEED_RELEASE: ${FEED_RELEASE:-24.10}
    volumes:
      - data_objects_vol:/mnt

  report-formats:
    image: registry.community.greenbone.net/community/report-formats:${VERSION_LATEST:-latest}
    <<: *basic
    deploy:
      <<: *basic-deploy-conf
    environment:
      FEED_RELEASE: ${FEED_RELEASE:-24.10}
    volumes:
      - data_objects_vol:/mnt

  gpg-data:
    image: registry.community.greenbone.net/community/gpg-data:${VERSION_LATEST:-latest}
    <<: *basic
    deploy:
      <<: *basic-deploy-conf
    volumes:
      - gpg_data_vol:/mnt

  gvm-tools:
    image: registry.community.greenbone.net/community/gvm-tools:${VERSION_LATEST:-latest}
    <<: *basic
    deploy:
      <<: *basic-deploy-conf
    volumes:
      - gvmd_socket_vol:/run/gvmd
      - ospd_openvas_socket_vol:/run/ospd

  # Sets log level of openvas to the set LOG_LEVEL within the env
  # and changes log output to /var/log/openvas instead /var/log/gvm
  # to reduce likelihood of unwanted log interferences
  configure-openvas:
    image: registry.community.greenbone.net/community/openvas-scanner:${VERSION_NOTUS_SCANNER:-stable}
    <<: *basic
    deploy:
      <<: *basic-deploy-conf
    volumes:
      - openvas_data_vol:/mnt
      - openvas_log_data_vol:/var/log/openvas
    command:
      - /bin/sh
      - -c
      - |
        printf "table_driven_lsc = yes\nopenvasd_server = http://openvasd:80\n" > /mnt/openvas.conf
        sed "s/127/128/" /etc/openvas/openvas_log.conf | sed 's/gvm/openvas/' > /mnt/openvas_log.conf
        chmod 644 /mnt/openvas.conf
        chmod 644 /mnt/openvas_log.conf
        touch /var/log/openvas/openvas.log
        chmod 666 /var/log/openvas/openvas.log

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
    driver_opts:
      encrypted: "true"
  proxy:
    external: true

volumes:
  gpg_data_vol:
  scap_data_vol:
  cert_data_vol:
  data_objects_vol:
  gvmd_data_vol:
  psql_data_vol:
  vt_data_vol:
  notus_data_vol:
  psql_socket_vol:
  gvmd_socket_vol:
  ospd_openvas_socket_vol:
  redis_socket_vol:
  openvas_data_vol:
  openvas_log_data_vol:
# configs:
#   openvas_config:
#     file: $PWD/config/openvas.conf
