---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.swarm.lbswarm=${LB_SWARM:-true}
    - traefik.swarm.network=proxy
    - traefik.http.routers.invoiceshelf.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.invoiceshelf.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.invoiceshelf.tls=true
    - traefik.http.routers.invoiceshelf.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.invoiceshelf.service=invoiceshelf
    - traefik.http.services.invoiceshelf.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.invoiceshelf.loadbalancer.server.port=${PORT:-80}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: any
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-1}
      memory: ${RESOURCES_LIMITS_MEMORY:-1g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges=true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  networks:
    default: {}
  healthcheck:
    disable: true
  restart: always

################################################################################
################################################################################
################################################################################
services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  invoiceshelf:
    # https://hub.docker.com/r/invoiceshelf/invoiceshelf
    image: invoiceshelf/invoiceshelf:${VERSION_INVOICE_SHELF:-latest}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    cap_add:
      - ALL
    secrets:
      - mariadb_user_password
    environment:
      PHP_TZ: ${PHP_TZ:-Europe/Berlin} # UTC
      TIMEZONE: ${TIMEZONE:-Europe/Berlin} # UTC
      APP_NAME: ${APP_NAME:-InvoiceShelf}
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}

      DB_CONNECTION: mariadb
      DB_HOST: ${DB_HOST:-mariadb}
      DB_PORT: 3306
      DB_DATABASE: ${MARIADB_DATABASE:-invoiceshelf}
      DB_USERNAME: ${MARIADB_USER:-invoiceshelf}
      DB_PASSWORD_FILE: /run/secrets/mariadb_user_password
      CACHE_STORE: file
      # STARTUP_DELAY: ${STARTUP_DELAY:-0}
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      SESSION_ENCRYPT: false
      SESSION_PATH: /

      SESSION_DOMAIN: ${DOMAIN?domain variable not set}
      SANCTUM_STATEFUL_DOMAINS: ${DOMAIN?domain variable not set}
      APP_URL: https://${DOMAIN?domain variable not set}
      TRUSTED_PROXIES: "*"

      # - MAIL_DRIVER=smtp
      # - MAIL_HOST=smtp.mailtrap.io
      # - MAIL_PORT=2525
      # - MAIL_USERNAME=null
      # - MAIL_PASSWORD=null
      # - MAIL_PASSWORD_FILE=<filename>
      # - MAIL_ENCRYPTION=null
    volumes:
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      - data:/data
      - conf:/conf
    networks:
      default: {}
      proxy: {}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -kIf ${PROTOCOL:-http}://127.0.0.1:${PORT:-80} > /dev/null 2>&1 || exit 1",
        ]
      start_period: 10s
      interval: 10s
      timeout: 3s
      retries: 10

  ##############################################################################
  ##############################################################################
  ##############################################################################
  mariadb:
    # https://hub.docker.com/_/mariadb
    image: mariadb:${VERSION_MARIADB:-11.8}
    <<: *basic
    deploy:
      <<: *basic-deploy
      resources:
        limits:
          cpus: ${RESOURCES_LIMITS_CPUS_MARIADB:-1}
          memory: ${RESOURCES_LIMITS_MEMORY_MARIADB:-512M}
        reservations:
          cpus: ${RESOURCES_RESERVATIONS_CPUS_MARIADB:-0.001}
          memory: ${RESOURCES_RESERVATIONS_MEMORY_MARIADB:-32m}
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    secrets:
      - mariadb_user_password
    environment:
      TZ: ${TZ:-Europe/Berlin}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-invoiceshelf}
      MARIADB_USER: ${MARIADB_USER:-invoiceshelf}
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_user_password
      MARIADB_RANDOM_ROOT_PASSWORD: ${MARIADB_RANDOM_ROOT_PASSWORD:-true}
    volumes:
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      - mariadb:/var/lib/mysql
    command:
      - --log-bin=mysql-bin
      - --expire-logs-days=90
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 2s
      interval: 5s
      timeout: 3s
      retries: 5

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-overlay}
    attachable: true
    driver_opts:
      encrypted: "true"
  proxy:
    external: true

volumes:
  data: {}
  conf: {}
  mariadb: {}

secrets:
  mariadb_user_password:
    file: config/secrets/mariadb_user_password.txt
