version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  wg-easy:
    image: weejewel/wg-easy:${VERSION:-latest}
    env_file: .env
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      fsize: -1
      as: -1
    deploy:
      mode: replicated
      # mode: global
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          # - "node.id==${NODE_ID}"
          - "node.role==${NODE_ROLE:-manager}"
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=${LB_SWARM:-true}
        - traefik.docker.network=proxy
        - traefik.http.routers.wg-easy.entrypoints=https
        - traefik.http.routers.wg-easy.rule=Host(`${DOMAIN?domain variable not set}`)
        - traefik.http.routers.wg-easy.tls=true
        - traefik.http.routers.wg-easy.service=wg-easy
        - traefik.http.services.wg-easy.loadbalancer.server.scheme=${PROTOCOL:-http}
        - traefik.http.services.wg-easy.loadbalancer.server.port=${PORT:-51821}
        - traefik.http.routers.wg-easy.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    ports:
      - target: 51820
        published: ${PORT:-51820}
        protocol: udp
        mode: host
      - target: 51821
        published: ${PORT:-51821}
        protocol: tcp
        mode: host
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      WG_HOST: ${DOMAIN?domain variable not set}
      # Optional:
      # PASSWORD: ${PASSWORD}
      # WG_PORT: ${WG_PORT:-51820}
      # WG_DEFAULT_ADDRESS: ${WG_DEFAULT_ADDRESS:-10.8.0.x}
      WG_DEFAULT_DNS: ${WG_DEFAULT_DNS:-1.1.1.1}
      # WG_MTU: ${WG_MTU:-1420}
      # WG_ALLOWED_IPS: ${WG_ALLOWED_IPS:-192.168.0.0/16}
      # WG_PRE_UP: ${WG_PRE_UP:-echo "Pre Up" > /etc/wireguard/pre-up.txt}
      # WG_POST_UP: ${WG_POST_UP:-echo "Post Up" > /etc/wireguard/post-up.txt}
      # WG_PRE_DOWN: ${WG_PRE_DOWN:-echo "Pre Down" > /etc/wireguard/pre-down.txt}
      # WG_POST_DOWN: ${WG_POST_DOWN:-echo "Post Down" > /etc/wireguard/post-down.txt}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/etc/wireguard
    networks:
      default: {}
      # proxy: {}
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
  # proxy:
  #   external: true

volumes:
  data: {}
