---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.swarm.lbswarm=${LB_SWARM:-true}
    - traefik.swarm.network=proxy
    - traefik.http.routers.forgejo.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.forgejo.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.forgejo.tls=true
    - traefik.http.routers.forgejo.tls.certresolver=${CERT_RESOLVER:-}
    - traefik.http.routers.forgejo.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.forgejo.service=forgejo
    - traefik.http.services.forgejo.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.forgejo.loadbalancer.server.port=${PORT:-3000}

    # - traefik.tcp.routers.forgejo-ssh.entrypoints=${TRAEFIK_ENTRYPOINT:-ssh}
    # - traefik.tcp.routers.forgejo-ssh.rule=HostSNI(`${DOMAIN?domain variable not set}`)
    # - traefik.tcp.routers.forgejo-ssh.tls=true
    # - traefik.tcp.routers.forgejo-ssh.tls.passthrough=true
    # - traefik.tcp.routers.forgejo-ssh.tls.certresolver=${CERT_RESOLVER:-}
    # - traefik.tcp.routers.forgejo-ssh.middlewares=${MIDDLEWARE_SECURED_SSH:-default-whitelist}
    # - traefik.tcp.routers.forgejo-ssh.service=forgejo-ssh
    # - traefik.tcp.services.forgejo-ssh.loadbalancer.server.port=${PORT_SSH:-22}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: any
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-1}
      memory: ${RESOURCES_LIMITS_MEMORY:-1g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  # mem_limit: ${RESOURCES_LIMITS_MEMORY:-1g}
  networks:
    default: {}
  healthcheck:
    disable: true
  tmpfs:
    - /tmp:rw,relatime,size=512m,nodev,nosuid,noexec
  restart: always

################################################################################
################################################################################
################################################################################
services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  forgejo:
    # https://codeberg.org/forgejo/-/packages/container/forgejo
    image: codeberg.org/forgejo/forgejo:${VERSION:-16}
    <<:
      - *basic
      # - *basic-deploy-labels
    deploy:
      <<:
        - *basic-deploy
        - *basic-deploy-labels
    cap_add:
      - CHOWN # Allows changing file ownership (`chown`,`chgrp`)
      - FOWNER # Overrides file ownership checks (`chmod`,`kill`)
      - SETGID # Allows setting group ID (`setgid`,`newgrp`,`chgrp`,`setregid()`)
      - SETUID # Allows setting user ID (`setuid`,`su`,`sudo`,`passwd`)
      - SYS_CHROOT # for chroot with ssh
    ports:
      - target: ${PORT_SSH:-22}
        published: ${PORT_SSH_PUBLISH:-2222}
        protocol: tcp
        mode: host
    environment:
      USER_UID: ${USER_UID:-1000}
      USER_GID: ${USER_GID:-1000}
      TZ: ${TIMEZONE:-Europe/Berlin}
      # https://forgejo.org/docs/latest/admin/config-cheat-sheet/
      # - Basic Format:   FORGEJO__[SECTION]__[KEY]
      # - DEFAULT Format: FORGEJO____[KEY]
      # DEFAULT
      FORGEJO____APP_NAME: "${APP_NAME:-Forgejo}"
      FORGEJO____APP_SLOGAN: "${APP_SLOGAN:-Beyond coding. We Forge.}"

      # SERVER
      FORGEJO__server__ROOT_URL: https://${DOMAIN?domain variable not set}
      FORGEJO__server__DOMAIN: ${DOMAIN?domain variable not set}
      FORGEJO__server__HTTP_PORT: ${PORT:-3000}
      FORGEJO__server__DISABLE_SSH: ${FORGEJO_DISABLE_SSH:-false}
      FORGEJO__server__SSH_DOMAIN: ${DOMAIN?domain variable not set}
      FORGEJO__server__SSH_LISTEN_PORT: ${PORT_SSH:-22}
      FORGEJO__server__SSH_PORT: ${PORT_SSH_PUBLISH:-2222}
      # FORGEJO__server__SSH_CHROOT: "/"

      # SECURITY
      FORGEJO__security__GLOBAL_TWO_FACTOR_REQUIREMENT: all
      FORGEJO__security__PASSWORD_COMPLEXITY: "lower,upper,digit,spec" # pragma: allowlist secret

      # DATABASE
      FORGEJO__database__DB_TYPE: sqlite3
      FORGEJO__database__Path: /data/gitea/gitea.db

      # FORGEJO__indexer__MAX_FILE_SIZE: 1073741824
      # FORGEJO__git__MAX_GIT_DIFF_LINES: 100000
      # FORGEJO__git__MAX_GIT_DIFF_LINE_CHARACTERS: 100000
      # FORGEJO__git__MAX_GIT_DIFF_FILES: 10000
      # FORGEJO__quota__ENABLED: "false"

      # ACTIONS (enabled by default; runner = docker-compose.runner.yaml)
      FORGEJO__actions__ENABLED: ${FORGEJO__actions__ENABLED:-true}
      # FORGEJO__actions__DEFAULT_ACTIONS_URL: https://github.com # default: https://data.forgejo.org
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/data
    networks:
      default: {}
      proxy: {}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -ksSfo /dev/null ${PROTOCOL:-http}://127.0.0.1:${PORT:-3000}/api/healthz || exit 1",
        ]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 3

################################################################################
################################################################################
################################################################################
networks:
  default:
    internal: true
    driver: ${NETWORK_MODE:-overlay}
    attachable: true
    driver_opts:
      encrypted: "true"
  proxy:
    external: true

volumes:
  # sudo apt install nfs-common
  data:
    # driver: local
    # driver_opts:
    #   type: nfs
    #   o: nfsvers=4.2,addr=${NFS_HOST?nfs host is not defined},rsize=2097152,wsize=2097152,tcp,nconnect=${NFS_NCON:-8}
    #   device: ":${NFS_PATH?nfs path is not defined}${SERVICE_NAME_POST:-}"
