---
version: "3.8"

################################################################################
################################################################################
################################################################################
services:
  ##############################################################################
  ##############################################################################
  ##############################################################################

  ##############################################################################
  ##############################################################################
  ##############################################################################
  redis:
    # https://hub.docker.com/_/redis
    image: redis:${VERSION_REDIS:-7.2.3-alpine}
    # <<: *basic
    # deploy:
    #   <<: *basic-deploy
    cap_add:
      - SETGID
      - SETUID
    volumes:
      - redis:/data
    command: --save 300 1 --loglevel warning --stats-interval 300
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 5s
      interval: 10s
      retries: 5
      timeout: 3s

  ##############################################################################
  ##############################################################################
  ##############################################################################
  postgresql:
    # https://hub.docker.com/_/postgres
    image: postgres:${VERSION_POSTGRESQL:-16.1-alpine}
    # <<: *basic
    # deploy:
    #   <<: *basic-deploy
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    secrets:
      - postgres_password_file
    environment:
      POSTGRES_DB: ${PG_DB:-postgresql}
      POSTGRES_USER: ${PG_USER:-postgresql}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password_file
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      default: {}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 5s
      interval: 10s
      retries: 5
      timeout: 3s

  ##############################################################################
  ##############################################################################
  ##############################################################################
  mariadb:
    # https://hub.docker.com/_/mariadb
    image: mariadb:${VERSION_MARIADB:-11.2.2}
    # <<: *basic
    # deploy:
    #   <<: *basic-deploy
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    secrets:
      - mariadb_root_password
      - mariadb_user_password
    environment:
      TZ: ${TZ:-Europe/Berlin}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-mariadb}
      MARIADB_USER: ${MARIADB_USER:-mariadb}
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_user_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      # MARIADB_RANDOM_ROOT_PASSWORD: ${MARIADB_RANDOM_ROOT_PASSWORD:-true}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - mariadb:/var/lib/mysql
    command:
      - --log-bin=mysql-bin
      - --expire-logs-days=90
    networks:
      default: {}
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh --no-defaults"]
      start_period: 5s
      interval: 10s
      retries: 5
      timeout: 3s

################################################################################
################################################################################
################################################################################

volumes:
  redis: {}
  postgresql: {}
  mariadb: {}

secrets:
  postgres_password_file:
    file: config/secrets/postgres_password_file.txt
  mariadb_root_password:
    file: config/secrets/mariadb_root_password.txt
  mariadb_user_password:
    file: config/secrets/mariadb_user_password.txt
