ARG VERSION_ALPINE=3.16.2
FROM alpine:${VERSION_ALPINE}

# ------------------------------------------------------------------------------

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="MVladislav version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="MVladislav"

# ------------------------------------------------------------------------------

ENV DEBIAN_FRONTEND noninteractive
ENV PHP_EXTRA_CONFIGURE_ARGS --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data

# ------------------------------------------------------------------------------

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN \
  echo "**** install MAIN packages ****" \
  apk update
apk add --update \
  git \
  wget \
  curl \
  bash

RUN \
  echo "**** cleanup ****" &&
  rm -rf \
    /var/cache/apk/*

# ------------------------------------------------------------------------------

# ADD OTHER CODES HERE

# ------------------------------------------------------------------------------

USER 1000:1000

# ------------------------------------------------------------------------------

# configure working directory
WORKDIR /app
# expose tcp port
EXPOSE 80/tcp
# set volumes
VOLUME ["/app", "/var/log"]

# configure entry point
COPY --chmod=750 config/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
COPY config/supervisord.conf /etc/supervisord.conf
ENTRYPOINT [ "/usr/local/bin/docker-entrypoint.sh" ]
CMD ["/bin/bash","-c","/usr/bin/supervisord -c /etc/supervisord.conf --nodaemon"]
