# Use specific Alpine version as base image
ARG VERSION_ALPINE=3.16.2
FROM alpine:${VERSION_ALPINE}

# ------------------------------------------------------------------------------

# Set version and maintainer labels
ARG BUILD_DATE
ARG VERSION
LABEL build_version="MVladislav version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="MVladislav"

# ------------------------------------------------------------------------------

# Set environment variables for non-interactive apt-get and PHP configuration
ENV DEBIAN_FRONTEND=noninteractive \
    PHP_EXTRA_CONFIGURE_ARGS="--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data"

# ------------------------------------------------------------------------------

# Install essential packages and clean up
RUN echo "**** Install MAIN packages ****" && \
    apk update && \
    apk add --no-cache \
      git \
      wget \
      curl \
      bash && \
    echo "**** Clean up ****" && \
    rm -rf /var/cache/apk/*

# ------------------------------------------------------------------------------

# ADD OTHER CODES HERE

# ------------------------------------------------------------------------------

# Set the user to a non-root user for security
USER 1000:1000

# ------------------------------------------------------------------------------

# Configure working directory and expose ports
WORKDIR /app
EXPOSE 80/tcp

# Set volumes for app and logs
VOLUME ["/app", "/var/log"]

# ------------------------------------------------------------------------------

# Configure entry point and command
COPY --chmod=750 config/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
COPY config/supervisord.conf /etc/supervisord.conf
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["/bin/bash", "-c", "/usr/bin/supervisord -c /etc/supervisord.conf --nodaemon"]
