ARG VERSION_PHP=7.4
ARG VERSION_UBUNTU=22.10

FROM ubuntu:${VERSION_UBUNTU}
# FROM ghcr.io/linuxserver/baseimage-ubuntu:bionic
# FROM ghcr.io/linuxserver/baseimage-ubuntu:arm64v8-bionic
# FROM ubuntu:latest

FROM php:${VERSION_PHP}-apache-stretch
FROM php:${VERSION_PHP}-fpm-alpine

FROM node:lts-alpine as frontend

# ------------------------------------------------------------------------------

# set version label
ARG BUILD_DATE=$(date +"%Y-%m-%d")
ARG VERSION=latest
LABEL build_version="MVladislav :: version - '${VERSION}' :: build-date - '${BUILD_DATE}'"
LABEL maintainer="MVladislav"
LABEL org.opencontainers.image.description="example official docker container."

# ------------------------------------------------------------------------------

ENV DEBIAN_FRONTEND noninteractive
ENV PHP_EXTRA_CONFIGURE_ARGS --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data
ENV PATH /usr/local/bin:$PATH

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# ------------------------------------------------------------------------------

## Fix some issues with APT packages.
## See https://github.com/dotcloud/docker/issues/1024
RUN dpkg-divert --local --rename --add /sbin/initctl
RUN ln -sf /bin/true /sbin/initctl

## Replace the 'ischroot' tool to make it always return true.
## Prevent initscripts updates from breaking /dev/shm.
## https://journal.paul.querna.org/articles/2013/10/15/docker-ubuntu-on-rackspace/
## https://bugs.launchpad.net/launchpad/+bug/974584
RUN dpkg-divert --local --rename --add /usr/bin/ischroot
RUN ln -sf /bin/true /usr/bin/ischroot

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8

# ------------------------------------------------------------------------------

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL C.UTF-8

# ------------------------------------------------------------------------------

RUN \
  echo "**** BASE => UPDATE :: INSTALL :: CLEAN ****" && \
  apt-get update -q && \
  apt-get install -y --no-install-recommends \
    # language
    locales \
    apt-utils \
    language-pack-en \
    # defaults \
    git \
    vim \
    curl \
    wget \
    apt-transport-https \
    ca-certificates \
    iproute2 \
    supervisor \
    make \
    build-essential \
  && \
  apt-get clean && \
  rm -rf \
    /tmp/* \
    /var/tmp/* \
    /var/lib/apt/lists/* \
    /var/log/* \
    /var/www \
    /usr/src/*

# ------------------------------------------------------------------------------

# LANG SETUP
RUN locale-gen en_US.UTF-8

# ------------------------------------------------------------------------------

# ADD OTHER CODES HERE

# ------------------------------------------------------------------------------

USER 1000:1000

# ------------------------------------------------------------------------------

# configure working directory
WORKDIR /app
# expose tcp port
EXPOSE 80/tcp
# set volumes
VOLUME /app
VOLUME /var/log

# configure entry point
COPY --chmod=750 config/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
COPY config/supervisord.conf /etc/supervisord.conf
ENTRYPOINT [ "/usr/local/bin/docker-entrypoint.sh" ]
CMD ["/bin/bash","-c","/usr/bin/supervisord -c /etc/supervisord.conf --nodaemon"]
