---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.swarm.lbswarm=${LB_SWARM:-true}
    - traefik.swarm.network=proxy
    - traefik.http.routers.coder.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.coder.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.coder.tls=true
    - traefik.http.routers.coder.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.coder.service=coder
    - traefik.http.services.coder.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.coder.loadbalancer.server.port=${PORT:-7080}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: any
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-2}
      memory: ${RESOURCES_LIMITS_MEMORY:-4g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  networks:
    default: {}
  healthcheck:
    disable: true
  tmpfs:
    - /tmp
  restart: always

################################################################################
################################################################################
################################################################################
services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  coder:
    # https://github.com/coder/coder/pkgs/container/coder
    image: ghcr.io/coder/coder:${VERSION_CODER:-v2.26.2}
    <<:
      - *basic
      - *basic-deploy-labels
    deploy:
      <<:
        - *basic-deploy
        - *basic-deploy-labels
    # user: "1000:${GID:-982}"
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-coder}:${POSTGRES_PASSWORD_TMP}@postgresql/${POSTGRES_DB:-coder}?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      # CODER_ACCESS_URL: https://${DOMAIN?domain variable not set}
      CODER_ACCESS_URL: "http://coder:7080"
      CODER_WILDCARD_ACCESS_URL: "*.${DOMAIN?domain variable not set}"

      CODER_TELEMETRY_ENABLE: ${CODER_TELEMETRY_ENABLE:-false}
      CODER_BLOCK_DIRECT: ${CODER_BLOCK_DIRECT:-true}
      CODER_DERP_SERVER_STUN_ADDRESSES: ${CODER_DERP_SERVER_STUN_ADDRESSES:-disable}
      CODER_UPDATE_CHECK: ${CODER_UPDATE_CHECK:-false}

      CODER_TLS_CERT_FILE: /var/coder/ca.pem
      CODER_TLS_CLIENT_AUTH: "none"
    configs:
      - source: ca_cert_file
        target: /var/coder/ca.pem
        mode: 0444
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default: {}
      proxy: {}

  ##############################################################################
  ##############################################################################
  ##############################################################################
  postgresql:
    # https://hub.docker.com/_/postgres
    image: postgres:${VERSION_POSTGRESQL:-17.5-alpine}
    <<: *basic
    deploy:
      <<: *basic-deploy
      resources:
        limits:
          cpus: ${RESOURCES_LIMITS_CPUS_POSTGRESQL:-1}
          memory: ${RESOURCES_LIMITS_MEMORY_POSTGRESQL:-512m}
        reservations:
          cpus: ${RESOURCES_RESERVATIONS_CPUS_POSTGRESQL:-0.001}
          memory: ${RESOURCES_RESERVATIONS_MEMORY_POSTGRESQL:-32m}
    cap_add:
      - CHOWN
      - FOWNER
      - DAC_READ_SEARCH
      - SETUID
      - SETGID
    secrets:
      - postgres_password_file
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-coder}
      POSTGRES_USER: ${POSTGRES_USER:-coder}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password_file
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 2s
      interval: 5s
      timeout: 3s
      retries: 5

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-overlay}
    attachable: true
    driver_opts:
      encrypted: "true"
  proxy:
    external: true

volumes:
  postgresql: {}

configs:
  ca_cert_file:
    file: $PWD/config/ca.pem

secrets:
  postgres_password_file:
    file: config/secrets/postgres_password_file.txt
