---
x-basic-deploy-labels: &basic-deploy-labels
  labels:
    - traefik.enable=true
    - traefik.swarm.lbswarm=${LB_SWARM:-true}
    - traefik.swarm.network=proxy
    - traefik.http.routers.fireflyiii.entrypoints=${TRAEFIK_ENTRYPOINT:-https}
    - traefik.http.routers.fireflyiii.rule=Host(`${DOMAIN?domain variable not set}`)
    - traefik.http.routers.fireflyiii.tls=true
    - traefik.http.routers.fireflyiii.middlewares=${MIDDLEWARE_SECURED:-default-secured@file}
    - traefik.http.routers.fireflyiii.service=fireflyiii
    - traefik.http.services.fireflyiii.loadbalancer.server.scheme=${PROTOCOL:-http}
    - traefik.http.services.fireflyiii.loadbalancer.server.port=${PORT:-8080}

x-basic-deploy: &basic-deploy
  mode: replicated
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - "node.role==${NODE_ROLE:-manager}"
      - node.platform.os == linux
  update_config:
    order: stop-first
  restart_policy:
    condition: any
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-1}
      memory: ${RESOURCES_LIMITS_MEMORY:-1g}
    reservations:
      cpus: ${RESOURCES_RESERVATIONS_CPUS:-0.001}
      memory: ${RESOURCES_RESERVATIONS_MEMORY:-32m}

x-basic: &basic
  env_file: ${ENV_FILE:-.env}
  # cap_add:
  #   # https://dockerlabs.collabnix.com/advanced/security/capabilities/
  #   - CHOWN
  #   - DAC_OVERRIDE
  #   - DAC_READ_SEARCH
  #   - SETGID
  #   - SETUID
  #   - FOWNER
  #   - FSETID
  # cap_drop: ["ALL"]
  security_opt:
    - no-new-privileges:true
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 655360
      hard: 655360
    fsize: -1
    as: -1
  networks:
    default: {}
  healthcheck:
    disable: true
  restart: always

################################################################################
################################################################################
################################################################################

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  fireflyiii:
    # https://hub.docker.com/r/fireflyiii/core
    image: fireflyiii/core:${VERSION_FIREFLY:-version-6.1.25}
    <<: [*basic, *basic-deploy-labels]
    deploy:
      <<: [*basic-deploy, *basic-deploy-labels]
    secrets:
      - site_owner_conf
      - app_key_file_password
      - mariadb_user_password
    environment:
      SITE_OWNER_FILE: /run/secrets/site_owner_conf
      APP_KEY_FILE: /run/secrets/app_key_file_password

      APP_URL: "https://${DOMAIN?domain variable not set}"
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-**}

      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE:-de_DE}
      DEFAULT_LOCALE: ${DEFAULT_LOCALE:-equal}
      TZ: ${TZ:-Europe/Berlin}

      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-false}
      LOG_CHANNEL: ${LOG_CHANNEL:-stack}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL:-notice}
      AUDIT_LOG_LEVEL: ${AUDIT_LOG_LEVEL:-emergency}
      AUDIT_LOG_CHANNEL: ${AUDIT_LOG_CHANNEL:-}

      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST:-mariadb}
      DB_PORT: ${DB_PORT:-3306}
      DB_USERNAME: ${MARIADB_USER:-firefly}
      DB_DATABASE: ${MARIADB_USER:-firefly}
      DB_PASSWORD_FILE: /run/secrets/mariadb_user_password

      # If you're looking for performance improvements, you could install memcached or redis
      CACHE_DRIVER: ${CACHE_DRIVER:-file}
      SESSION_DRIVER: ${SESSION_DRIVER:-file}

      COOKIE_PATH: ${COOKIE_PATH:-"/"}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN:-}
      COOKIE_SECURE: ${COOKIE_SECURE:-false}
      COOKIE_SAMESITE: ${COOKIE_SAMESITE:-lax}

      SEND_ERROR_MESSAGE: ${SEND_ERROR_MESSAGE:-true}
      SEND_REPORT_JOURNALS: ${SEND_REPORT_JOURNALS:-true}
      ENABLE_EXTERNAL_MAP: ${ENABLE_EXTERNAL_MAP:-false}
      ENABLE_EXTERNAL_RATES: ${ENABLE_EXTERNAL_RATES:-false}
      MAP_DEFAULT_LAT: ${MAP_DEFAULT_LAT:-51.983333}
      MAP_DEFAULT_LONG: ${MAP_DEFAULT_LONG:-5.916667}
      MAP_DEFAULT_ZOOM: ${MAP_DEFAULT_ZOOM:-6}

      # Firefly III supports a few authentication methods:
      # - 'web' (default, uses built in DB)
      # - 'remote_user_guard' for Authelia etc
      # Read more about these settings in the documentation.
      # https://docs.firefly-iii.org/how-to/firefly-iii/advanced/authentication/
      AUTHENTICATION_GUARD: ${AUTHENTICATION_GUARD:-web}
      AUTHENTICATION_GUARD_HEADER: ${AUTHENTICATION_GUARD_HEADER:-REMOTE_USER}
      AUTHENTICATION_GUARD_EMAIL: ${AUTHENTICATION_GUARD_EMAIL:-}
      PASSPORT_PRIVATE_KEY: ${PASSPORT_PRIVATE_KEY:-}
      PASSPORT_PUBLIC_KEY: ${PASSPORT_PUBLIC_KEY:-}
      DISABLE_FRAME_HEADER: ${DISABLE_FRAME_HEADER:-false}
      DISABLE_CSP_HEADER: ${DISABLE_CSP_HEADER:-false}
      ALLOW_WEBHOOKS: ${ALLOW_WEBHOOKS:-false}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - upload:/var/www/html/storage/upload
    networks:
      default: {}
      proxy: {}

  ##############################################################################
  ##############################################################################
  ##############################################################################
  mariadb:
    # https://hub.docker.com/_/mariadb
    image: mariadb:${VERSION_MARIADB:-11.6.2}
    <<: *basic
    deploy:
      <<: *basic-deploy
      resources:
        limits:
          cpus: ${RESOURCES_LIMITS_CPUS_MARIADB:-1}
          memory: ${RESOURCES_LIMITS_MEMORY_MARIADB:-512M}
        reservations:
          cpus: ${RESOURCES_RESERVATIONS_CPUS_MARIADB:-0.001}
          memory: ${RESOURCES_RESERVATIONS_MEMORY_MARIADB:-32m}
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    secrets:
      - mariadb_user_password
    environment:
      TZ: ${TZ:-Europe/Berlin}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-firefly}
      MARIADB_USER: ${MARIADB_USER:-firefly}
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_user_password
      MARIADB_RANDOM_ROOT_PASSWORD: ${MARIADB_RANDOM_ROOT_PASSWORD:-true}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - mariadb:/var/lib/mysql
    command:
      - --log-bin=mysql-bin
      - --expire-logs-days=7
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 10s
      retries: 5
      timeout: 3s

  ##############################################################################
  ##############################################################################
  ##############################################################################
  fireflyiii_cron:
    # https://hub.docker.com/_/alpine
    image: alpine:${VERSION_ALPINE:-3.21.2}
    <<: *basic
    deploy:
      <<: *basic-deploy
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: >
      sh -c "echo \"0 3 * * *
      wget -qO- http://fireflyiii:8080/api/v1/cron/${STATIC_CRON_TOKEN}\"
      | crontab - && crond -f -L /dev/stdout"

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-overlay}
    attachable: true
    driver_opts:
      encrypted: "true"
  proxy:
    external: true

volumes:
  upload: {}
  mariadb: {}

secrets:
  site_owner_conf:
    file: config/secrets/site_owner_conf.txt
  app_key_file_password:
    file: config/secrets/app_key_file_password.txt
  mariadb_user_password:
    file: config/secrets/mariadb_user_password.txt
